### ISSUE TITLE
Race in client_pooled_socket_disconnected on tokio branch

### ISSUE THREAD

**Issue by alexcrichton** [hyperium/hyper#1003]
I'm seeing the `client_pooled_socket_disconnected` fail spuriously on the tokio branch, and I think that this may be related to connection pooling. There's a [`select`](https://github.com/hyperium/hyper/blob/35e23b78d569122cadda4f4481204b6ad0a9c6fa/src/client/mod.rs#L157) to take a connection from the pool and in parallel attempt a new connection, returning whichever is successful first. I think that the race here is what's causing the nondeterminism, and the problem is happening when the pooled connection here is pulled out.

The pooled connection is guaranteed to return a failure (e.g. broken pipe) b/c the connection is closed on the remote end. Is this a problem in general with pooled connections? Is there a location where the health of the connection is tested before it's used?  (I may have missed this)

**Comment by seanmonstar** [comment]
There is a health check before using (in Pool, the status is checked that it is still `Idle`, and not expired), and the hangup on the socket will trigger the status to be set to `disabled`. Unfortunately, the hangup may take some time to be received, and so it is possible for a client to try to start a new request on the socket before we know it has been closed.

For this test case, I've added a sleep to the core to wait for a few milliseconds, since the socket is local, the race was likely just scheduling between the server and client threads. The sleep should make it deterministic, allowing this test to check that disconnected sockets are tossed.

Separately, for the case when a client tries a socket before receiving HUP, hyper should do similar to what Go's http client does: check if the socket has been used before, and if it has, try to use a new socket. There is a field to track that on the `Pooled` type, but it will take a little more work to check it, and also make sure it's safe to retry the request (idempotent method, or body hasn't been written, etc).
