### ISSUE TITLE
Provide `From<Message> for Request`

### ISSUE THREAD

**Issue by alexcrichton** [hyperium/hyper#1036]
I've taken most of the ideas learned here about spawning servers back to tokio-proto in https://github.com/tokio-rs/tokio-proto/pull/135 and I believe the only remaining blocker for hyper being compatible with tokio-proto's `TcpServer` is the usage of `SocketAddr` in Hyper's request type. If this can be handled to implement `From<Message> for Request` then Hyper could leverage support in https://github.com/tokio-rs/tokio-proto/pull/130 to use `TcpServer` directly, especially when working with TLS connections where Hyper's conveniences won't be available.

Talking with @carllerche over lunch today one idea was to have the socket address be a member of the messages coming from the `Stream` going into tokio-proto. That way the message itself would contain the socket address. I could imagine this being implemented via a trait bound in Hyper perhaps? 

What do you think?

**Comment by seanmonstar** [comment]
That definitely sounds good. This is basically for this line: https://github.com/hyperium/hyper/blob/master/src/server/mod.rs#L258

So, `impl From<Message<ProtoRequest, http::TokioBody> for Request`? I could move the `SocketAddr` into the `ProtoRequest` type, but I don't know how someone would make use of this, since they cannot create those types...

**Comment by alexcrichton** [comment]
Yeah that's the impl I was thinking of. I don't think users would use this explicitly, but that way Hyper "as is" would hook into tokio-proto's `TcpServer` so that could be used off the bat.
