### ISSUE TITLE
How to use another async libs with hyper?

### ISSUE THREAD

**Issue by blackbeam** [hyperium/hyper#1067]
I've just tried to use `mysql_async` with hyper master and found that it is impossible with current `Send + Sync` bounds on `Http::bind` and `Server`.
I've also tried to satisfy `Send` and `Sync` for `mysql_async::Pool` but failed. I'm not even sure that it is possible.

Only solution i found is to clone hyper and remove `Sync + Send` bound.

Maybe there is another way? Did someone tried to compose another tokio-based async libs with hyper?

**Comment by seanmonstar** [comment]
Those bounds are only the constructor of `Service`s, the `NewService`. The `Service` itself doesn't need to be `Send + Sync`. This is because the `Server` in hyper may soon be able to make use of multiple threads if asked, and so the `NewService` constructor needs to be threadsafe.

This example in the [tokio docs](https://tokio.rs/docs/getting-started/db/) shows the ideas of how you can move the pool into the `NewService` constructor, and then just make clones of the pool for each `Service`. Note it uses the `minihttp` crate and `TcpServer`, which you can substitue as hyper's `Http::bind`. The missing piece might be the `move` part of the closure, but I cannot say without seeing.

----

Zooming out, if you're composing multiple things that all need a tokio reactor, you may not want `Http::bind`. `bind` is supposed to be an easy constructor for simple servers. You can hook up a `TcpListener` to a `Core` you already own, and pipe the incoming streams into `Http::bind_server`.
