### ISSUE TITLE
HTTPS connection don't use pool

### ISSUE THREAD

**Issue by pgerber** [hyperium/hyper#1086]
I have been been using a connection pool and it works just fine via HTTP. However, when using HTTPS observed a performance drop. Looking into it I noticed that for HTTP, connection are reused properly but for HTTPS it would appear that one connection is opened per request.

I'm not sure if this is an error on your side or just me using the library incorrectly. Either way, it might be a good idea to document the proper way to do this somewhere.

Here's the code I used:
```rust
let tls = hyper_rustls::TlsClient::new();
let connector = HttpsConnector::new(tls);
let pool = hyper::client::pool::Pool::with_connector(pool::Config { max_idle: 25 }, connector);
let client = Client::with_connector(pool);
let s3client = S3Client::with_request_dispatcher(client, credentials, endpoint.clone())
```

**Comment by shepmaster** [comment]
OP has also [cross-posted to Stack Overflow](http://stackoverflow.com/q/42739936/155423).

**Comment by seanmonstar** [comment]
@pgerber that looks like correct usage to me (I don't know much about `S3Client`).

Many have found that hyper does do connection pooling even with TLS, so there is perhaps something extra here that is going on. Let me list a few things that could be:

- Are all the requests being made at the same time, or at least before a previous request/response has finished? A connection is put back in the pool once the response has been read, and the pool will make use an idle connection if it's there, but if it isn't, it doesn't wait around. It starts a new connection immediately.
- Is the full response being read? If a response still has pending bytes to be read (hyper would know this either by counting after seeing the `Content-Length` header, or based on the chunk size during `Transfer-Encoding: chunked`), the response won't be put back in the pool. This is because hyper won't do extra reading that you don't ask for, and with bytes still pending, future responses would be behind the bytes that hyper won't read.
- Does this occur with other TLS implementations? I don't know much about rustls, I've most often seen people using `hyper_native_tls`.

**Comment by pgerber** [comment]
> Are all the requests being made at the same time, …
No, the pool is currently dedicated to a single thread doing one request after another. The code that does the request (the `S3Client` you can see in the code sample) is in another crate and I'd have to check if it does anything weird. I can't see why it would work with HTTP and not HTTPS though but I'll check to be sure.

> Is the full response being read
It's actually PUT requests, but yes, requests are completed before the next request is started.

> Does this occur with other TLS implementations?
I had already tested with `hyper-openssl` and just now tested `hyper_native_tls`. None of them work.

**Comment by seanmonstar** [comment]
> It's actually PUT requests, but yes, requests are completed before the next request is started.

To clarify, the response body must read also. If S3 is returning some JSON response of details, and you don't read it, that connection cannot be reused.

**Comment by pgerber** [comment]
It turned out that the S3 storage provider accidentally set the `Connection: close` header. They are still in early beta, so I'll forgive them.

@seanmonstar Thank you so much for your help!

**Comment by seanmonstar** [comment]
Ah, that would do it! I can't believe I forgot to mention that condition as well.
