### ISSUE TITLE
More allocator friendly Header definitions 

### ISSUE THREAD

**Issue by arthurprs** [hyperium/hyper#1104]
I was looking at https://github.com/TechEmpower/FrameworkBenchmarks/pull/2611 the other day and I noticed there's no way of using some Header types without allocating, like the `Server` header in the linked example.

It's not a problem per se but it's probably worth discussing as setting N headers could potentially allocate N times.

**Comment by seanmonstar** [comment]
Agreed. I starting with the most common, `Host`, but others should follow. Since changing the signature would be a breaking change anyways, it also makes sense to make the fields private and use constructors instead. That way we can start with `Cow` but we can switch to `Bytes` or something later in the future and not break. Some common headers that could beneift:

- Location
- Origin
- Referer
- Server
- UserAgent

**Comment by mcarlin** [comment]
@seanmonstar, I'm looking to start contributing here. Mind if I take a stab at it and convert over those headers you mentioned if you're not already working on it?

**Comment by seanmonstar** [comment]
@mcarlin That'd be great! I turned the list into checkboxes, ideally we can keep them up to date.

**Comment by seanmonstar** [comment]
The list of headers I made have all been converted. If there's changes want to a specific header, lets open specific issues. Thanks!
