### ISSUE TITLE
hyper::header::Cookie not hashable

### ISSUE THREAD

**Issue by dorfsmay** [hyperium/hyper#1139]
From what I can see hyper::header::Cookie provides cookies as separate "key=value" element, but there is no way to access the keys directly (let me know if I'm missing something here). I think there would be value to provide a way to access Cookies directly bye keys right in hyper rather than as a separate crate.

Are there reasons for not providing this? Is it worth adding a PR for it? Should this be done as part of hyper::header::Cookie, or as a separate struct (say hyper::header::hashedCookie)?

**Comment by seanmonstar** [comment]
I assume you mean that there isn't a way to store and access cookies by their name. That's correct, it is likely out of scope for hyper. There is a lot of good work in the [cookie](https://crates.io/crates/cookie) crate.

**Comment by dorfsmay** [comment]
Cookies are key to web server/client communication.

I agree that session management, keeping track of cookies etc... is out of scope for hyper, and as noted the cookie crate does a great job for this. But I think that any apps running on top of a web server will eventually need to look at cookies from requests, for all kind of reasons, and  for things simpler than session management. If splitting on the equal sign and provide a map to the cookies is out of scope, why wasn't splitting on the semi-colon and provide individual cookie "strings" not out of scope.

The effort to add this seems minimal, it's basically one struct and a couple of methods,. I'm happy to add a PR for this. Let me know your thoughts.

**Comment by seanmonstar** [comment]
Hyper actually used to depend on the cookie crate, and so you would have `Cookie` structs that you could poke at. The dependency was removed because cookie had an optional dependency of openssl, which caused a lot of problems. I recall discussion of eventually removing that.

I wouldn't say that parsing the cookie string into a struct with `name` and `value` and such is necessarily out of scope, but anything more than that likely is.

**Comment by dorfsmay** [comment]
This is being revisted in #1145.
