### ISSUE TITLE
Pass arguments when binding a service

### ISSUE THREAD

**Issue by glennpierce** [hyperium/hyper#1143]
Hi I have a very simple server based on the example
https://github.com/hyperium/hyper/blob/master/examples/server.rs

Is there any example of how to pass an object reference into the service  ?

Ie how can I pass a reference to each Echo instance so it can be used in the service implementation.

Thanks

**Comment by seanmonstar** [comment]
@glennpierce If I understand correctly, you mean such that your service struct has other properties? Like `struct Echo { foo: Something }`? Or specifically that that something is a `&Something`? If you mean a literal reference, then the answer is that you can't, at least not with the convenient methods.

If you wish to share a thing, you'll need to make use of `Arc`.

Alternatively, if you don't use `Http::bind`, and instead manage the `Core` yourself, then you make use of references, since you can guarantee the compiler the references won't live longer than the `Core`.

(I'm going to close this as a usage question, instead of an issue/bug.)
