### ISSUE TITLE
Manually creating hyper::server::Request's for unit testing services

### ISSUE THREAD

**Issue by tynor** [hyperium/hyper#1154]
Hello,

I'm playing around with Hyper's Tokio integration, but I'm running into a hiccup when trying to test my service. What I want to do is pass in a specially crafted `Request`, then just `.wait()` the future and check the result. But it seems like the only way to test a service is to create a full server (listening on a TCP socket) and send it a string for it to parse as a request.

That feels much more like an integration test to me, and it would be really nice to be able to test services (especially middleware) in isolation, with explicit requests, and expected responses.

Is there a reason behind exposing no interface for creating requests? Or maybe I'm just missing something in the docs?

**Comment by seanmonstar** [comment]
The reason was to be conservative, and allow hyper internals to change the way a `Request` is constructed without breaking backwards compatibility. However, as part of uniting the server and client types together in #1155, that would mean that the current `client::Request::new(method, uri)` would be usable with servers as well.

For now, I do recommend creating a server to run the tests, but a fix for #1155 is already in development, and I think it can be done without a breaking change, so 0.11 isn't blocked on it.

**Comment by tynor** [comment]
Oh, awesome, I didn't see #1155 when I was looking through the issue queue. Thank you (both for the answer and your work on Hyper in general.)

**Comment by tynor** [comment]
(And I actually just realized it was made after this one, no wonder. :P)
