### ISSUE TITLE
 hyper performance results

### ISSUE THREAD

**Issue by lslima91** [hyperium/hyper#1169]
Hi, thanks for the lib. 

Are these results expected considering the fact that the tested version points to this repo
https://www.techempower.com/benchmarks/#section=data-r14&hw=ph&test=plaintext

**Comment by seanmonstar** [comment]
Yes, those look correct. It's worth noting that the 'plaintext' section of those benchmarks is quite worthless, since it's testing for how fast a framework can process a bunch of pipelined requests. It's a situation that never happens in real life, since all browsers and clients don't use pipelined requests anymore.

Probably more interesting is the JSON results, or the results using queries (seems hyper doesn't have tests for those yet).

**Comment by daiheitan** [comment]
seems updated

https://www.techempower.com/benchmarks/#section=data-r14&hw=ph&test=json

**Comment by arthurprs** [comment]
json results look good, but there's probably room for improvement overall. Right now most of the effort is aimed towards releasing the new version on top of tokio.

**Comment by seanmonstar** [comment]
With the recent improvements leading up to v0.11 (now released), hyper did **much** better: https://www.techempower.com/benchmarks/previews/round15/#section=data-r15&hw=ph&test=json
