### ISSUE TITLE
Force push the gh-pages branch

### ISSUE THREAD

**Issue by dtolnay** [hyperium/hyper#1191]
The output of `git log --graph --all --pretty=format:"%h%d %s"` is annoying because the first 577 lines are all "rebuild pages" commits. Following every commit to master there is a commit to gh-pages, so this long gh-pages history will always show up first. In docs.sh it should force-push the gh-pages branch so there is only ever 1 commit on that branch.

**Comment by seanmonstar** [comment]
I've never tried to view the log like that before... This may be beyond my git knowledge, is there a way to wipe the history of a branch? Hm.. perhaps by finding the first commit of master, checking it out on gh-pages, then copying the contents over, and force pushing?

**Comment by dtolnay** [comment]
It is beyond my git knowledge too! A long time ago I found this awesome alias that I stuck in `.gitconfig` and have been using ever since.

```
[alias]
    lg = log --graph --all --color --pretty=format:\"%x1b[31m%h%x1b[32m%d%x1b[0m%x20%s\" -16
```

![selection_054](https://cloud.githubusercontent.com/assets/1940490/26559258/652dfe74-4463-11e7-842e-2f2e0e433ee1.png)

---

[This may be helpful.](https://github.com/brson/rust-cookbook/blob/440a39436ed9402996f12100c20b051bb69dde49/deploy.sh#L53-L60). It is doing `mdbook build` instead of `cargo doc` but the force push part should work the same.

**Comment by seanmonstar** [comment]
There was an attempt in #1495, but some concern around if gh-pages would build with dates in the past. I don't personally ever `git log --all` (my personal alias, `git l`, is just `git log --oneline -20 --no-merges`). As such, I'm going to close the issue, not because I'm against it (if someone provides a fix, cool!), but to remove it from the list of things that I look at to determine what is broken in hyper. Thanks!
