### ISSUE TITLE
Server response chunks not flushing

### ISSUE THREAD

**Issue by dylanede** [hyperium/hyper#1212]
(This is on master)

If I create a server that responds to a request with a response that has a body stream (of chunks) that is long-lived, I find that (on my machine at least) no data is actually sent to the client until a total of at least about 1024 characters have been sent (which may be made up of multiple chunks). Presumably hyper isn't flushing after sending each chunk into the TCP stream? I have to work around this by sending a dummy block of text at the start of each long-lived stream. After that initial block of text chunks seem to be sent to the client immediately.

Other than that, hyper has been brilliant for my use case so far, thanks!

**Comment by seanmonstar** [comment]
I can think of 2 possible things here: 

1. hyper keeps a write buffer, and flushes periodically (specifically, when tokio-proto triggers hyper's `poll_complete` method). Tokio should trigger that after a round of asking the body stream for any pending chunks. So, if you `body.start_send(chunk)` several times in a row, those chunks should be accumulated into a buffer in hyper, and then Tokio will ask hyper to flush.
2. TCP can also buffer things, because of Nagle's algorithm. This can be adjusted by setting `tcp.set_nodelay(true)` before giving the socket to hyper.

Some logging, either by connecting into hyper's logs, or something like wireshark to watch TCP, would help show more about what is happening.

**Comment by seanmonstar** [comment]
I'm going to close due to inactivity, but if you have more information, please share!
