### ISSUE TITLE
https removed in 0.11 release?

### ISSUE THREAD

**Issue by ThetaSinner** [hyperium/hyper#1218]
I have my Cargo.toml set to always use the latest hyper so I'll be moving 0.11 from 0.10.12 as of last night. I was using both http and https in my project. However when I've come to look at the docs and guide I can't find any mention of how to implement https. Nor can I see any mention of support being dropped in the changelog for this version.

Any help would be appreciated, I need to be able to send access tokens over https which is obviously innapropriate over http.

**Comment by dmizuk** [comment]
You can use [hyper-tls](/hyperium/hyper-tls) crate for the time being.

But unfortunately, it is not released to crates.io yet. So you need to use the git repository as the dependency.

**Comment by ThetaSinner** [comment]
Great, that'll work thanks.
I'm happy enough using the git repo for now.

**Comment by frewsxcv** [comment]
Looks like it's published now https://crates.io/crates/hyper-tls

**Comment by danger89** [comment]
So now I got a question related to this story...

What are the differences between:
* [hyper-tls](https://github.com/hyperium/hyper-tls)
* [hyper-native-tls](https://github.com/sfackler/hyper-native-tls)
* [hyper-openssl](https://github.com/sfackler/hyper-openssl)

I'm very confused as a user.

And which is the best SSL/TLS implementation to use now and in the (near) future??
I don't get it anymore.

**Comment by seanmonstar** [comment]
As of today (note, this could change as time goes on, so Future User, check):

- hyper-tls provides an `HttpsConnector` that works with hyper v0.11, that uses native-tls internally.
- hyper-native-tls works with hyper v0.10, using native-tls.
- hyper-openssl works with hyper v0.10, using openssl.

hyper-tls could go away in the future, if there is no longer a need. For now, the need is because hyper v0.11 is super new, and the ecosystem hasn't had time to catch up yet.

All this said: **you probably should just use [reqwest](https://crates.io/crates/reqwest)** instead of hyper directly, if you have need of an HTTP client. It will take care of this for you.

**Comment by danger89** [comment]
Ow thanks, I didn't know about reqwest. The better the abstraction the easier for everyone. From httparse to hyper, from hyper to reqwest. From reqwest to AI that will destroy earth.

**Comment by ThetaSinner** [comment]
It's taken me a while to get around to implementing this in my project. I hadn't looked closely enough at hyper-tls to notice that it works with client configuration.
I should have said in my original question that it's https on the server that I need.
