### ISSUE TITLE
Testing the remote address of a Request

### ISSUE THREAD

**Issue by brendanzab** [hyperium/hyper#1258]
I'm trying to test a reverse proxy `Service` that adds the remote address in an `X-Forwarded-For` header. Unfortunately I can't test this in a unit test because I'm unable to set the field on the `Response` type. Is there some reason why there is no `Request::set_remote_addr` method?

**Comment by seanmonstar** [comment]
The reason is probably because no one ever thought about it. 😄 

The `remote_addr` is kind of weakly supported, since not all transports even have the concept of a socket address (like Unix Domain Sockets). For that reason, the tokio-proto architecture doesn't provide it. The only way it would be set is if you used `Http::bind`, since that can use the knowledge of being bound over `TcpStream` to fetch the address.

I wonder if the address should be moved out of the `Request` entirely, and be something you can set on a `Service` struct, perhaps required by a custom `NewService`.

**Comment by brendanzab** [comment]
So for now I just decided to get my users to [pass in the `remote_addr` manually](https://docs.rs/hyper-reverse-proxy/0.2.1/hyper_reverse_proxy/struct.ReverseProxy.html#method.new).

**Comment by seanmonstar** [comment]
The `Request` and `Response` from the [http crate](https://crates.io/crates/http) don't have fields for the socket addresses. These types will soon replace hyper's. Getting address is probably something that should be done by creating a listener and then storing the adress on a `Service`.
