### ISSUE TITLE
Re-implement io::Read for Response?

### ISSUE THREAD

**Issue by legolord208** [hyperium/hyper#1273]
It had it for version 0.9, but since 0.11 it only has futures, which makes it harder to collect stuff to a string et.c.

**Comment by seanmonstar** [comment]
A `Response` has a [`Stream`](https://docs.rs/futures/0.1.14/futures/stream/trait.Stream.html), which is quite different from a thing that can be read from. As seen in the [guides](https://hyper.rs/guides), it's possible to easily concat the body.

It would also be fairly straight forward for some type to wrap a `Response`, and include a buffer, and then `Read` could be implemented by either polling the stream, or copy bytes from the yielded buffer.

(Also, since a readable response would mean the client, have you seen [reqwest](https://crates.io/crates/reqwest)?)

**Comment by legolord208** [comment]
A stream might be easy enough to use on it's own, but when it comes to updating Hyper 0.9 to 0.11 it's really difficult to change every single `read_to_string`. Currently I made a io::Read wrapper instead.
