### ISSUE TITLE
Re-Exporting Header Structs

### ISSUE THREAD

**Issue by SeunLanLege** [hyperium/hyper#1301]
I rely heavily on intellij Intellisense and spent the last hour searching for where the `ContentType` header was exported from only to find some sort of macro sorcery. I'm new to rust (~2months). What exactly is this macro doing? why wasn't the header structs exported _the normal way_ ?

https://github.com/hyperium/hyper/blob/50fd4ab96daaadc10be9317dc0d365c7a5ebed5e/src/header/mod.rs#L350-L364

was it too much work? i'm happy to help out if it was.

**Comment by SeunLanLege** [comment]
@seanmonstar

**Comment by mehcode** [comment]
@SeunLanLege The `ContentType` header is actually defined here:

https://github.com/hyperium/hyper/blob/9bb71b9bbfedc4b47c96dd83efd75f852abced6b/src/header/common/content_type.rs#L48

There is a documented `header!` macro it uses to define itself with here: https://docs.rs/hyper/0.11.2/hyper/header/index.html#defining-custom-headers

---

[That bit of code](https://github.com/hyperium/hyper/blob/50fd4ab96daaadc10be9317dc0d365c7a5ebed5e/src/header/mod.rs#L350-L364) you linked is internal-only (not exported) and used in the [`Extend impl`](https://github.com/hyperium/hyper/blob/50fd4ab96daaadc10be9317dc0d365c7a5ebed5e/src/header/mod.rs#L628) which is when you take one set of headers and _extend_ it with another one. I'm completely sure why its doing what it's doing but @seanmonstar can probably answer that.

**Comment by SeunLanLege** [comment]
Oh i see, but problem with that approach is that we lose intellisense. :disappointed:

**Comment by SeunLanLege** [comment]
what would it take to write them as structs?

**Comment by seanmonstar** [comment]
The linked macro for literals is internal code. It's definitely unrelated.

The type you're looking for *is* a struct, and it is exported at `hyper::header::ContentType`. The macro used to define it just removes the need to write out some common pieces, only requiring to write the parts of the `Header` impl that are different from other headers. The macro expands to a `pub struct ContentType(pub Mime);`.

What is the actual issue here? Intellisense cannot understand macros in Rust?

**Comment by SeunLanLege** [comment]
> What is the actual issue here? Intellisense cannot understand macros in Rust?

that would appear to be the case.
