### ISSUE TITLE
direction on async hyper body stream parsing

### ISSUE THREAD

**Issue by softprops** [hyperium/hyper#1335]
In the past, I've had great success with leveraging hyper's Response.bytes() impl to feed into serde's json deserializer to stream out json provided by a servers which stream json in chunks over a period of time. 

After upgrading to hyper 0.11 I think I want do target response.body() which returns a stream of chunks but each chunk doesn't seem to contain a parsable json object in isolation. I've hit a few bumps in the past by serde changing its own interface for creating iterators of json over non finite chunks of data. I believe the latest interface is a [StreamDeserializer](https://docs.serde.rs/serde_json/de/struct.StreamDeserializer.html) type which may take a read.

A more concrete picture of what I'm doing is taking some potentially streamed json from [kubernetes cluster](https://github.com/softprops/lux/blob/8b07c45edd6f6139090a6012b62a758bbfb687ff/src/logs.rs#L101) and streaming the [json parsing](https://github.com/softprops/lux/blob/master/src/pod.rs#L46) with serde.

I'm now again struggling to figure out how to put these two pieces together in a compatible way. Since hyper's body now returns a Stream type it may be more ideal to transform that into a stream of `serde_json::Value` types but without each chunk being a individually parseable thing. I could use some direction with your expertise. A fair answer is that this is just no longer possible with the async api.

**Comment by srijs** [comment]
Hi @softprops!

Unfortunately I don't think there is a straight-forward way to achieve this :( But that doesn't mean it's not possible!

You are right that the chunks very likely don't contain a parseable json object, so the challenge would be to change this so that each item coming down the stream is a line of text from the body, so that we then use `Stream::and_then` to parse each line using serde. Basically splitting the byte stream on `\n`.

I've written a bit of code [here](https://play.rust-lang.org/?gist=971e438cabd6f91efb76b7e45b15edf3&version=stable), to illustrate what that could look like.

After you've obtained such a stream, you can then use `Stream::map_err` and `Stream::and_then` to parse it:

```rust
enum Error {
    Hyper(hyper::Error),
    FromUtf8(FromUtf8Error),
    Serde(serde_json::Error)
}

impl From<FromUtf8Error> for Error {
    fn from(err: FromUtf8Error) -> Error {
        Error::FromUtf8(err)
    }
}

// somewhere down the line...

let stream = Lines::new(response.body().map_err(Error::Hyper))
    .and_then(|line| serde_json::from_str(&line).map_err(Error::Serde))
```

Hope that helps! Feel free to ask if this is unclear or you have any further questions :)

**Comment by softprops** [comment]
Thanks. I think that gives me some ideas!

**Comment by softprops** [comment]
@srijs I just tried this and actually this works amazingly as-is for my usecase. Would it be okay with you if I I wrapped this up in a crate? I can't be the first person to hit this problem and am sure this would be useful to others?

**Comment by srijs** [comment]
Not at all, go for it!

Odds are there's a couple of edge-casey bugs in there though, so you
might want to write a couple of tests around it just to make sure ;)

**Comment by softprops** [comment]
Thanks man. Thanks for contributing to the rust communities awesomeness score!

**Comment by seanmonstar** [comment]
An issue you may encounter is that a chunk can come over the socket that isn't a full JSON object, because it was bigger than could fit in the packet. Or you could have a packet arrive with a full object, and the start of another. So, you'd need to be able to buffer any partial chunks.
