### ISSUE TITLE
Uri::fragment() is only available in test

### ISSUE THREAD

**Issue by maghoff** [hyperium/hyper#1345]
`Uri::fragment()` is conditionally included with `cfg(test)`: https://github.com/hyperium/hyper/blob/9c80fdbb9e2ffb717e7126a453e815e8c47be459/src/uri.rs#L222-L228

It seems a weird omission from a basic API which already offers `path` and `query`. Could it be the case that this is simply a mistake, and `fragment` should be included unconditionally?

**Comment by seanmonstar** [comment]
It wasn't a *mistake*, it was intentional. Perhaps a comment should have been left explaining the "why". Here's some why:

The server *should* never receive the fragment, and so it being on the type might make people think they should reach for it (and perhaps route on it). And clients should also never actually send a fragment to the server.

I do realize there is legitimate reason for a client to interact with a fragment before or after issuing a request to a server, but there were concerns (at least my own) of misusing it

It should perhaps be noted that `hyper::Uri` will soon be replaced with [`http::Uri`](https://github.com/hyperium/http/issues/127), and maybe that issue would be best for discussing how to expose it?

**Comment by maghoff** [comment]
> The server should never receive the fragment
You are right. I was confused on this point, but have now re-read the spec regarding it :)

I no longer feel that I should be able to access the fragment where I have tried to do so, so I will close the issue. A code comment explaining the "why" might be appropriate :)

Thanks for your quick response :+1:
