### ISSUE TITLE
 Implementing From<SetCookie> for Cookie

### ISSUE THREAD

**Issue by TheSirC** [hyperium/hyper#1351]
Following [this thread](https://users.rust-lang.org/t/reqwest-transfering-setcookie-from-a-response-to-a-request/12577?u=thesirc) and [this one](https://users.rust-lang.org/t/implementing-from-setcookie-for-cookie-for-hyper/12880), I have "_implemented_" `From<SetCookie> for Cookie` [here](https://github.com/TheSirC/mootse-watcher/blob/develop/src/main.rs#L70).
Before opening any pull request, I would like to know : 

1. if you had any comments on the implementation
2. where should I modify things (not to break everything in the process 😅 )

Thanks for taking the time to read this newbie issue !

**Comment by seanmonstar** [comment]
Not providing easy conversions is partly on purpose, because it can be easy to then disobey the rules given in `Set-Cookie`, such as respecting the path and domain. That said, I realize even if hyper doesn't provide an easy conversion, people will still just force a conversion and accidentally ignore the rules anyways...

Many people may find that using the [cookie](https://crates.io/crates/cookie) crate may help parse all this stuff in the first place.

There is also [an issue in reqwest](https://github.com/seanmonstar/reqwest/issues/14) to add proper cookie jar support, that would add these cookies for you, but also properly obey the rest of the `Set-Cookie` directives...

**Comment by seanmonstar** [comment]
For now, the new version of hyper won't be including the typed headers directly, so I'm closing this here as a won't fix.
