### ISSUE TITLE
Unable to read body data of Request (always freezes)

### ISSUE THREAD

**Issue by XX** [hyperium/hyper#1356]
When I try read body data of the `Request`, then `wait()` blocks the running thread forever:

```rust
let (method, uri, version, headers, body) = request.deconstruct();
println!("Read body");
let total = body.concat2().and_then(|chunk| {
    let vec = chunk.iter().cloned().collect();
    let stringify = String::from_utf8(vec).unwrap();
    println!("stringify: {}", stringify);
    future::ok(stringify)
}).wait().unwrap();
println!("Body: {:?}", total);
```

When request body is not empty (for POST method), only "Read body" line is printed and the entire application freezes. Why is this happening?

**Comment by KodrAus** [comment]
Does this still block forever if you use [`tokio_core::reactor::Core.run()`](https://docs.rs/tokio-core/0.1.10/tokio_core/reactor/struct.Core.html#method.run) and pass your `total` future in instead of calling `total.wait()`?

**Comment by KodrAus** [comment]
Specifically I think that because `hyper`s body is effectively a channel with a sender and a receiver if you block on the receiver end (in your call to `concat2`) on the same thread that's driving the sender then you'll deadlock, because the receiver will prevent the sender from making any progress.

At least that's how I think the `Body` works here.

**Comment by XX** [comment]
@KodrAus Thanks for the answer. If I pass `total` future in instead of calling `total.wait()`, there is no blocking.
