### ISSUE TITLE
Add example for multilpe concurrent rest requests

### ISSUE THREAD

**Issue by fulara** [hyperium/hyper#1407]
I think an example where where multiple rest requests are being made and they are executed concurrently would be nice 

Lets say that there are two services, and we want to query them both at once. We dont care about the sequence, just that both are executed ( started ) at the same time.

**Comment by seanmonstar** [comment]
Does this answer the question? https://hyper.rs/guides/client/advanced/#multiple-requests

**Comment by fulara** [comment]
But it seems that these are executed sequentially? Is there any way to do it concurrently? Or do I have to spawn mujltiple workers myself?

**Comment by seanmonstar** [comment]
They do happen concurrently. One or the other may finish first. The order of the prints with the status code depends on the server. However, in this example, since they are joined, it does mean that it waits for both to finish to get the bodies. You could change the code to act on the bodies also, adding `and_then` after the `concat2`, for instance.

**Comment by fulara** [comment]
Great, excellent, apologies for wasting your time.

You can close the ticket then.

Just one more question - I think its more question towards tokio not hyper, so apologies about that.
If I wanted to push tasks into core from other thread than the one that is invoking work() how would I go about that?

**Comment by seanmonstar** [comment]
You take a reference to the `Core` via a `Handle` or a `Remote`. `Handle` is for same-thread. `Remote` can be sent to other threads. So `core.remote()`.
