### ISSUE TITLE
Logging outbound request from client

### ISSUE THREAD

**Issue by oa-metaswitch** [hyperium/hyper#1418]
Hi. I'm trying to write a tracer which logs exactly what requests get sent over the wire, and preferably including local and remote ip/port. I realize hyper is agnostic to transport, but is there some way of logging the request and response struct, and getting passed a reference to the transport for diagnostics purposes?

Has anyone done anything like that before?

**Comment by seanmonstar** [comment]
You can sort of do what you want, but not all of it is especially easy.

For logging request and response, that you can do by logging whatever you want just before calling `client.request` (or `client.call`), and you can log the response returned by the future, for example:

```rust
debug!("req = {:?}", req);
client.request(req)
    .map(|res| {
        debug!("res = {:?}", res);
        res
    })
```

In order to get a reference to the transport being used, you'd probably need to write a custom `Connect` so that you can return a transport that can log some instances about itself.

Probably this is also related to #1402.

(As this seems more like a question around how to do something in hyper, and not a bug that something doesn't work, I'm going to close for now.)

**Comment by oa-metaswitch** [comment]
Hi Sean.

Thanks for the quick reply, and sorry: I should have been more specific. I've already attempted something like what you describe above, however: hyper tacks on a few headers (transfer encoding, Date header, etc) before sending, and I'd like to log the request as it actually goes out over the wire, including those headers. 

I currently have a tracer that works by implementing a custom connect and wrapping the TcpStream, but to sensibly log the request I then find I have to re-parse it to get the method, headers, body, etc.

It would be nice to have a logging callback, maybe somewhere around https://docs.rs/hyper/0.11.12/src/hyper/client/mod.rs.html#193, that could pass a reference to the transport and the request after the extra headers have been added. Is that sensible? Otherwise, is there a way of doing this already?

Thanks.

**Comment by sfackler** [comment]
Do you know what these kinds of APIs look like in other HTTP client libraries?

**Comment by oa-metaswitch** [comment]
@sfackler sorry for taking a while to respond. 

I don't really have any examples of this in other client libraries, but I don't think there are many other libraries that would have a need for it. Put differently, I think hyper is a bit more opaque than other HTTP client libraries I've worked with. In particular
 
- It's agnostic to the transport layer, which makes it hard to access information about the TCP connection.
- It's also opaque in its request processing, in that it does not give you easy access to the request just before it's sent on the wire. 

Don't get me wrong, I think it's great that it works like this, I would just really like some way to special-case for TCP connections when I have a need to access the transport layer.
