### ISSUE TITLE
Assigning a streaming request body

### ISSUE THREAD

**Issue by matthauck** [hyperium/hyper#1436]
It is a bit unfortunate that as far as I can tell the only way to set a response body is by having the entire request body in memory. The one exception perhaps is setting a body with a `futures::sync::mpsc::Receiver`, which is a bit clunky. It would be very cool to just be able to assign something that implements `Read` or `Stream` or something. 

Use case: streaming a large file directly into a request or implementing an http proxy.

Maybe there's something there that I'm missing?

**Comment by seanmonstar** [comment]
You can set the body type of a response to any custom `Stream` type. The default is just easy to use in simple cases, but frameworks or users can change to a stream better suited to their needs. You'd do so like this:

```rust
impl Service for FileServe {
    type Response = Response<FsReadStream>;
    // ...
}
```

Related guides:

- https://hyper.rs/guides/server/echo/#body-streams
- https://hyper.rs/guides/server/response_strategies/

**Comment by sfackler** [comment]
You can use the Stream.forward method to write a stream to the mpsc sender.

**Comment by matthauck** [comment]
Interesting. I was looking at [the docs](https://docs.rs/hyper/0.11.16/hyper/struct.Body.html#impl-From<Receiver<Result<Chunk, Error>>>) for `hyper::Body` and didn't see any `From<Stream>`.

I will take a closer look at those links, but I'm a bit skeptical as both of those docs are in the server guide section. 

At the very least, it may be interesting at least to add to the client guide a example of how to stream a large file upload.

**Comment by seanmonstar** [comment]
Yea, there can't be a `From<Stream>`, since that's a trait, not a concrete type. Since `hyper::Body` is meant to be easy to use in common cases, maybe it's worth adding a `Body::boxed_stream(s) -> Body`?

Oh, I read the original comment about setting a response body, and assumed you were talking about the server.

For a client, you can also set a custom stream type, it's just a little different to configure, since you don't define a `Service` when using a client. This is the current way (I'm aware it's awkward, and should probably be done in a different way in 0.12):

```rust
let client = Client::configure()
    .body::<FsReadStream>()
    .build(&handle);
```

https://docs.rs/hyper/0.11.*/hyper/client/struct.Config.html#method.body

**Comment by matthauck** [comment]
Aha, and my rust beginner status shines through. :) 

Great, I will give that a look.

**Comment by seanmonstar** [comment]
I'm going to close this, as it doesn't seem to be an actual bug. :)
