### ISSUE TITLE
How to use the Serve object ?

### ISSUE THREAD

**Issue by George3d6** [hyperium/hyper#1440]
I've been trying to make a hyper server run on the same context/core as a tokio TCP server.

However this kind of usage seems to be poorly documented (or I'm unable to find/read the docs properly). currently my code looks like this:

```
    let mut core = Core::new().unwrap();
    let handle = core.handle();

    let server_addr = "127.0.0.1:1834".parse().unwrap();
    let serve = Http::new().serve_addr_handle(&server_addr, &handle, || Ok(DataServer)).unwrap();

    let server = serve.for_each(move |f| {
        Ok(())
    }).map_err(|err| {
        println!("IO error {:?}", err);
    });

    current_thread::run(move |_| {
        current_thread::spawn(server);
        current_thread::spawn(receptor); // <--- This is that other TCP server, it works just fine
    });
```

This code runs just fine and is listening on port 1832, however the call() method of DataServer is never called.

Any idea what am I doing wrong here and how I should go about this ?

**Comment by seanmonstar** [comment]
You're right, it **is** poorly documented. The reason is because it's a newer feature, but I wasn't quite certain how well it would play with the newer tokio and futures. As that becomes more certain, the whooe server module will get some documentation about the 2ish APIs, low level and high level.

For your immediate case: `Serve` is a stream of `Connection`s, bound to a service. However, each `Connection` is itself its own `Future`, needing to be executed. In your for_each call, you should spawn them onto the executor.

**Comment by seanmonstar** [comment]
Also, you likely didn't show your whole program, so maybe it's not an issue, but that `Core` you created will need to be running for the IO in hyper to work.

**Comment by George3d6** [comment]
Sorry, the code is actually wrong, I modified it a lot to figure out how to make it run and this version is plain wrong since it doesn't use the core I created for IO but rather the current thread :/

The version of the code I ended up using is:

   ```
    let server_addr = "127.0.0.1:1834".parse().unwrap();
    let server = Http::new().bind(&server_addr,|| Ok(DataServer)).unwrap();

    let movable_handle = server.handle();
    let receptor = listener.incoming().for_each(move |stream| {
        //movable_handle used here to spawn futures
    });

    server.handle().spawn(receptor);
    server.run();
```

Which basically means I'm taking the handle from the server and running everything on whatever  context/core the server is using (which I assume is on the current thread of execution).

The alternative would be to create the core and use a handle from it to spawn all processes and I assume that would work, though I'm happier with this (less code and as far as I can tell exact same result).

What I'm unsure of is if there is a way to accomplish this (running two servers on the same event loop) w/o this  "hack" and without going into tokio-core, as in, only using things like current_thread and in some way binding the execution of the server to that ?

**Comment by seanmonstar** [comment]
The unfortunate thing is that you end up with 2 reactors (epoll event notifiers), one for HTTP and one for your TCP server. The TCP one is probably tokio's new default, in a separate thread.

I don't know the best way to get them working together, I probably wouldn't recommend trying to do it just yet. hyper will upgrade to the new tokio soon, once the futures 0.2 release happens.

cc @carllerche

**Comment by George3d6** [comment]
Wait, so the above snippet of code would create tow reactors ? I assumed that in that case the TCP server would just use the hyper's server thread+notification-loop.

Also, a bit ot, but does tokio use epoll instead of poll ? And if so, would this stop hyper from working on non-linux systems ? Or would it just fall back to poll ?

**Comment by seanmonstar** [comment]
Well, in neither example do I see how you create the TCP server, so I can't say for certain, but seeing the `current_thread` API suggests to me that you're using `tokio`, not `tokio_core`. If you're using both, then yes, they have currently have incompatible reactors, and so likely using 2.

Tokio uses [mio](https://github.com/carllerche/mio), which abstracts over the various selection strategies in a cross platform way (so epoll on linux, kqueue on bsd, IOCP on windows).

**Comment by George3d6** [comment]
I'm not using current_thread anymore, but yes, the TCP server is created using Tokio not tokio_core and ps shows the program apparently spawns to threads... -_-.

I'm quite unsure why the TCP servers would use it's own thread though, I spwan it using the server's handler and I spwan the futures inside it's callback using the same handler (not current thread).

Can a process two separate futures be spawned on the same handler but use different threads to run ? Or does the server just start a new thread by default when I call `server.run();` and the main thread stays inactive ?

**Comment by seanmonstar** [comment]
The new design of Tokio is that by default, it spawns a global reactor, putting it in its own thread. This happens if you use `Handle::default()` (or functions on things like `TcpListener` that don't take a `Handle` argument). You can prevent the global by creating a reactor yourself, and passing references to it (its `Handle`).

**However!** hyper does not yet use new Tokio, but instead the older tokio-core, So, it doesn't know about global reactors, and in fact, its `Handle` is technically a different type, so you cannot share them. This means that to drive your newer-Tokio TCP server, and the older-tokio-core hyper server, you need 2 reactors.

This might seem like poop, but don't worry, you just jumped in right during a transition period. Tokio is transitioning, and the new `tokio` 0.1 crate is a preview of the new design. The `futures` crate will see a list of breaking changes to version 0.2 in a couple weeks, and when that happens, `tokio` will upgrade to 0.2, and hyper will upgrade to both. After that, you no longer have the situation you're in at the moment.

**Comment by seanmonstar** [comment]
(I'm going to close this issue, since it isn't about a bug in hyper.)
