### ISSUE TITLE
Absolute Uri

### ISSUE THREAD

**Issue by kevinastone** [hyperium/hyper#1452]
It would be helpful to have a helper function that creates absolute Uri from the given request as part of Hyper.

Iron has such a function:
https://github.com/iron/iron/blob/master/src/request/mod.rs#L78-L118

**Comment by seanmonstar** [comment]
Unfortunately, for HTTP/1, this requires information that hyper may not contain. For instance, since hyper is generic over the server connection streams, it doesn't know if it is supposed to `http` or `https`. Also, if the request is `HTTP/1.0`, a `Host` header may not be present.

I'd suggest that this is something that frameworks can provide, as they are in a better position to know all of the required information.
