### ISSUE TITLE
examples/client.rs not building

### ISSUE THREAD

**Issue by stevedonovan** [hyperium/hyper#1522]
Error says it all:
```
10 | use hyper::service::service_fn;
   |            ^^^^^^^ Could not find `service` in `hyper`
```
Am I missing something really obvious? (Using stable 1.26 here)

**Comment by davidbarsky** [comment]
The examples directory is using the master branch of Hyper, which will be 0.12. The current release of Hyper on crates.io is 0.11.27, which lacks the `hyper::service` module. Since you're seeing this build error, I'm _assuming_ that you're pulling Hyper from crates.io and not the mainline branch of `hyperium/hyper`.

If you replace `hyper = "0.11"` in your Cargo.toml with `hyper = { git = "https://github.com/hyperium/hyper" }`, your project should build correctly.

**Comment by stevedonovan** [comment]
Thanks, man! This was obvious in hindsight. Shall we keep this open as a marker until 0.12 lands on crates.io?

**Comment by davidbarsky** [comment]
Maybe! That said, I've opened an PR to alleviate this issue.
