### ISSUE TITLE
Why does a Service's Future need to implement Send in 0.12 ?

### ISSUE THREAD

**Issue by Globidev** [hyperium/hyper#1540]
Hello and thank you for your work on this library

I was trying to upgrade my application from hyper 0.11 to 0.12 and I noticed that for a `Serve<I, S>` to implement `Stream`, it now [requires `<S::Service as Service>::Future` to be **Send + 'static**](https://docs.rs/hyper/latest/hyper/server/conn/struct.Serve.html#impl-Stream)

Note that you can actually create a `Serve` using [hyper::conn:Http::serve_addr](https://docs.rs/hyper/latest/hyper/server/conn/struct.Http.html#method.serve_addr) without those restrictions but since it does not implement `Stream`, I am pretty sure that it is not really usable ?

This restriction wasn't present in 0.11 and I'm wondering why it is now because it feels like I suddenly have to design my application around parallelism issues

**Comment by seanmonstar** [comment]
The reason for the change is because those bounds are both what the `futures` crate and Tokio were both moving towards for the [`Executor` trait](https://docs.rs/futures/0.2.*/futures/executor/trait.Executor.html). I realize it is a bit more inconvenient, and I don't especially love needing to require them. It didn't seem like there was a good solution otherwise, but I'm always open to hearing some.

**Comment by Globidev** [comment]
I see, that actually make sense since executors will most likely involve a thread pool of sorts.
I won't pretend that I am competent enough to suggest an alternative, I was mainly just curious :)

Anyway, thanks a lot for taking the time to answer!

Closing.
