### ISSUE TITLE
Automatically encode a HTTP body

### ISSUE THREAD

**Issue by DustinByfuglien** [hyperium/hyper#1579]
Good day!

As I understand Hyper automatically decode HTTP1.1-response Body with "content-encoding". So Body comes to my handler in decoded (i.e. unzipped) form.
My proxy needs to edit it, then gzip it and translate HTTP-response to client. Is there enough to keep "content-encoding: gzip" header and Hyper automatically gzip it? Or I need to compress it handy?
Can you give me example please?

**Comment by seanmonstar** [comment]
hyper doesn't automatically decode or encode anything besides `Transfer-Encoding: chunked`. To handle zipped content, you'd need to pass chunks you receive in the `Request` to something that can decode, and likewise pass content to something that can encode before being used as a body in the `Response`.

For the `Response`, it's possible to implement `hyper::body::Payload` to encapsulate that encoding, instead of passing a `hyper::Body` directly in the `Response`.

(As this isn't a bug in hyper, I'm going to close the issue.)
