### ISSUE TITLE
Add an example for client making HTTP GET call, then parsing body into JSON

### ISSUE THREAD

**Issue by brandonros** [hyperium/hyper#1581]
The current example out there fails to show how to concatenate a body, then do anything with it.

I'm new to Rust and I've been struggling for 2 hours on something that I'd imagine most beginners would benefit from having a clear documented example on.

Here is a very verbose, no magic node.js example:

```javascript
var rp = require('request-promise');

async function getResponseBody(uri) {
  var options = {
    uri: uri,
    simple: false,
    resolveWithFullResponse: true
  };

  var response = await rp.get(options);

  return JSON.parse(response.body);
}

(async function() {
  console.log(await getResponseBody("http://api.icndb.com/jokes/random"));
})();
```

**Comment by seanmonstar** [comment]
It does seem like either we could add a second example in `examples/`, or add a better second guide at https://hyper.rs/guides/client/`.

For an immediate answer, you've got two-ish easy possibilities:

- [`Stream::concat2`](https://docs.rs/futures/0.1.*/futures/stream/trait.Stream.html#method.concat2): returns a `Future<Item=Chunk>`, so that at the end, all the data of the body has been conbined into a single buffer, allowing to easily then pass into `serde_json`.
- [`Stream::collect`](https://docs.rs/futures/0.1.*/futures/stream/trait.Stream.html#method.collect): returns a `Future<Item=Vec<Chunk>>`, where you have a list of buffers of the full body, but not yet combined into a single buffer. This second option *can* be useful if you don't need to copy all the bytes into a single buffer, in which case this reduces a bunch of copies, but can be a little more difficult if you really need a single buffer.

An example using the first:

```rust
client
    .get(uri)
    .and_then(|res| {
        res.into_body().concat2()
    })
    .and_then(|body| {
        // try to parse as json, perhaps with serde_json
        serde_json::from_slice(&body)
            .map_err(|e| handle_json_error(e))
    })
```

For anyone wanting this already implemented, you may wish to look at [reqwest](https://crates.io/crates/reqwest), which has this built-n as [`Response::json()`](https://docs.rs/reqwest/0.8.*reqwest/struct.Response.html#method.json)

**Comment by brandonros** [comment]
Super grateful for this!

My one qualm is... how often does an application make an HTTP request and then exit? It is a good example of the library and what it offers no doubt, but I think a better example would be showing a function that returns a future that resolves with the deserialized body, which I think is a more common real world use case.

In the example I posted above, you're able to use the return value of the HTTP JSON GETting function for however you want, then logged from the calling function.

**Comment by seanmonstar** [comment]
@brandonros fair. The example merged is *nearly* that. If you wanted, I'd be fine with the `fetch_json` to be changed to return `impl Future<Item=Vec<User>, Error=Box<std::error::Error>>`.

**Comment by brandonros** [comment]
```
21 | fn fetch_json(url: hyper::Uri) -> impl Future<Item=Vec<User>, Error=Box<std::error::Error>> {
   |                                                                         ^^^^^^^^^^^^^^^^^ expected lifetime parameter
   |
   = help: this function's return type contains a borrowed value with an elided lifetime, but the lifetime cannot be derived from the arguments
   = help: consider giving it an explicit bounded or 'static lifetime
```

```
#![deny(warnings)]
extern crate hyper;
#[macro_use]
extern crate serde_derive;
extern crate serde;
extern crate serde_json;

use hyper::Client;
use hyper::rt::{self, Future, Stream};

fn main() {
    let url = "http://jsonplaceholder.typicode.com/users".parse().unwrap();

    // Run the runtime with the future trying to fetch, parse and print json.
    //
    // Note that in more complicated use cases, the runtime should probably
    // run on its own, and futures should just be spawned into it.
    rt::run(fetch_json(url));
}

fn fetch_json(url: hyper::Uri) -> impl Future<Item=Vec<User>, Error=Box<std::error::Error>> {
    let client = Client::new();

    client
        // Fetch the url...
        .get(url)
        // And then, if we get a response back...
        .and_then(|res| {
            // asynchronously concatenate chunks of the body
            res.into_body().concat2()
        })
        // use the body after concatenation
        .and_then(|body| {
            serde_json::from_slice(&body).expect("parse json");
        })
}

#[derive(Deserialize, Debug)]
struct User {
    id: i32,
    name: String,
}
```

**Comment by seanmonstar** [comment]
Now *that* looks odd. `Box<Trait>` should be fine and assume `'static`... I wonder if the rules are different when returning `impl Trait<Types>`? Perhaps `Box<std::error::Error + 'static>`?

Either way, the code would need to be updated slightly, since there's 2 different error types needing to be coerced into a `Box<Error>`. But would the change I mentioned be what you were looking for?

**Comment by brandonros** [comment]
Yes. I think people looking for the simplicity of `request-promise` will be happy to find this has been covered with your very fine Rust package. Without this, I know I'm personally left scratching my head saying "why would anybody who just wants to make an HTTP request and get some JSON sign up for this much pain"?

**Comment by ozgurakkurt** [comment]
I can improve the example to return the vector from get_json and then increment the id's of all users and then println! it in another function.

**Comment by ozgurakkurt** [comment]
Also I can add another example that is a server doing this.
