### ISSUE TITLE
Getting "message is incomplete" when sending request after Hyper upgrade

### ISSUE THREAD

**Issue by saarw** [hyperium/hyper#1582]
I'm trying to upgrade hyper, but getting the message "message is incomplete" from the client when trying to send the following
`Request::builder().method(Method::GET).uri(uri).header::<&str, &str>("Authorization", &format!("Bearer {}", self.api_key)).body(Body::empty()) `

It seems I can get the client to send the request if I specify an additional header like the one below, but that's clearly not correct as the 0 is not supposed to be a string, how can I specify an integer header value instead of the string? 
`.header::<&str, &str>("Content-Length", "0")`

I'm using a Client based on RustTLS HttpsConnector that uses an underlying regular hyper HttpConnector if that has anything to do with it.

**Comment by seanmonstar** [comment]
The "message is incomplete" error usually means the message read from the server wasn't complete... That's likely the problem we should look at!

For the second question, there's nothing wrong with specifying the content-length the way you did. However, it's not needed, since the body is `Body::empty()`.

**Comment by saarw** [comment]
Ok! Updated the title to reflect problem in the issue.

**Comment by saarw** [comment]
This seems fixed when upgrading from 0.12.2 -> 0.12.3. Thanks!
