### ISSUE TITLE
Provide a way to convert from http::Error into hyper::Error

### ISSUE THREAD

**Issue by matthauck** [hyperium/hyper#1623]
Trying to upgrade from hyper 0.11 to 0.12 and ended up kinda stuck on http::Error and hyper::Error, with no way I have found so far to construct one of these from the other. Since hyper depends on http and not the other way around, it seems that hyper should have a `From<http::Error>`.

For example, I have a type: 

```rust
pub type FutureResponse = Box<Future<Item = Response<Body>, Error = hyper::Error>>;
```

However, to be able to construct a Response, there, I have to use `Response::builder()` now to be able to set status codes / response headers, which in the end gives me a `Result<Response, http::Error>`, which cannot fit inside my `FutureResponse` type above, which is necessary for something like a `req.body().concat2().map(...)` future chain. Something like:

```rust
fn process_some_bits(req: Request<Body>) -> FutureResponse
{
    Box::new(req.body().concat2().map(move |data| {
        Response::builder().status(StatusCode::BAD_REQUEST).body(
            Body::from(format!("Failed on some stuff")),
        )
    }))
}
```

And I can't find a way to `.map_err(...)` and turn the http::Error into a hyper::Error to be able to standardize on just one of them. 

From the examples I saw in hyper, there are `.unwrap()`s all over the place when using `Response::builder()` which makes me sad and I think is indicative that something is wrong. I think this could be resolved simply by just allowing us to construct a hyper::Error from a http::Error.

**Comment by seanmonstar** [comment]
>  to be able to construct a Response, there, I have to use Response::builder()

You can also construct a `Response` directly, and mutate it without the builder. For your example:

```rust
let mut res = Response::new(Body::from(some_str));
*res.status_mut() = StatusCode::BAD_REQUEST;
```

The purpose of the builder is to provide an alternative, "easier" way of building requests and responses, where the errors returned are usually always going to be *programmer* errors. For that reason, the examples that show unwrapping is because in those examples, any error is a mistake in the program, and should just panic quickly. For instance, doing something like `Response::builder().status(1337)`. (The reason it returns an error instead of panicking internally is to allow the user to decide when to panic, or to try to use the builder with untrusted inputs without panicking.)

Seeing as your example is likely for a server, you probably *don't* want to return an `http::Error` for a server. Returning any error in the `Service` will tell hyper to tear down the connection immediately, whereas most servers would rather send back some 500 response because an internal error.

**Comment by matthauck** [comment]
I see. I didn't think i could mutate the status/headers after setting the body. I will give that a try.

**Comment by matthauck** [comment]
Thanks. That worked! It does feel a bit backwards to set the body before setting the status/headers, but that did the trick with no `.unwrap()`! :tada:
