### ISSUE TITLE
The presence of a duplicate header name in a response causes HeaderMap to have entries with None as key

### ISSUE THREAD

**Issue by ps1dr3x** [hyperium/hyper#1705]

**Comment by seanmonstar** [comment]
Would you be able to expand on what you mean?

**Comment by ps1dr3x** [comment]
I'll try to explain better. If a server responds to a request, and that response headers contains duplicated keys, eg:

> HTTP/1.1 200 OK
> Example-Header: example-value
> Example-Header: another-example-value

This code:

```
let (parts, body) = response.into_parts();
for header in parts.headers {
    println!("{:?}", header);
}
```
will print:

> ("Example-Header", "example-value")
> (None, "another-example-value")

**Comment by seanmonstar** [comment]
Ah, yes, that is expected behavior. If you look at the documentation for the [`IntoIterator for HeaderMap`](https://docs.rs/http/0.1.*/http/struct.HeaderMap.html) (you'll need to scroll to the bottom and expand it), it says:

> For each yielded item that has None provided for the HeaderName, then the associated header name is the same as that of the previously yielded item. The first yielded item will have HeaderName set.

The reason for this is because you're using the *consuming* iterator, which moves the keys and values out of the map. Since the key is only stored once, it can only be yielded once. If you use a *borrowed* iterator, then the references to the keys can be yielded multiple times, since it doesn't need to move the key out of the map.

```rust
let (parts, body) = response.into_parts();
for header in &parts.headers {
    println!("{:?}", header);
}
```

**Comment by ps1dr3x** [comment]
Ah, oops! I wasn't aware of that. I was wondering how a Map could not have some keys 🤷‍♂️

Thanks for the clarification!
