### ISSUE TITLE
A Server with a background process that would process a queue

### ISSUE THREAD

**Issue by salman-ca** [hyperium/hyper#1733]
Say I have a server similar to the [state example](https://github.com/hyperium/hyper/blob/master/examples/state.rs) except that something is being added to a queue e.g. the request ip address or something.

Now I want a separate thread/process to run in the background and every x seconds, it should take some messages off the queue.

Can you please direct me to what I should learn to do something like this?

**Comment by davidbarsky** [comment]
A good option would be to use [futures' mpsc](https://docs.rs/futures/0.1/futures/sync/mpsc/index.html) module. Unless you have good reason, I'd suggest skipping the “every `n` seconds” bit of your plan because handling backpressure gets trickier. However, if you _do_ have good reason, I'd suggest taking a look at Tokio's [Timer module](https://docs.rs/tokio/0.1/tokio/timer/index.html).

**Comment by davidbarsky** [comment]
@salman-ca: I'm going to guess that you've gotten this work by now, so I'll close this issue for now.
