### ISSUE TITLE
Why does hyper not close the future once it is complete?

### ISSUE THREAD

**Issue by lukaseller** [hyperium/hyper#1753]
I did implement a very basic hyper request and i noticed that the future does not seem to get closed once the request is finished. In the following example this would mean that _Done_ is never printed.

```
extern crate tokio;
extern crate futures;
extern crate hyper;

use futures::future::*;
use hyper::Client;

fn main() {
    let client = Client::new();
    let uri = "http://httpbin.org/ip".parse().unwrap();
    let task = client.get(uri)
            .and_then(|res| {
                println!("Response: {}", res.status());
                Ok(())
            })
            .map_err(|err| {
                println!("Error: {}", err);
            });

    tokio::run(task);
    println!("Done!");
}
```
What could be the reason for this?

My toml file is as follows:
```
[dependencies]
tokio = "0.1"
futures = "0.1"
hyper = "0.12"
```

Thanks in advance!

**Comment by davidbarsky** [comment]
I'd suggest importing `use tokio::runtime::Runtime` and running your task like:

```rust
let mut rt = Runtime::new()?;
rt.block_on(task);
```

Therefore, the full code example, assuming the 2018 edition of Rust, would be:

```rust
use tokio::runtime::Runtime;
use hyper::Client;

fn main() {
    let client = Client::new();
    let uri = "http://httpbin.org/ip".parse().unwrap();
    let task = client.get(uri)
            .and_then(|res| {
                println!("Response: {}", res.status());
                Ok(())
            })
            .map_err(|err| {
                println!("Error: {}", err);
            });

    let mut rt = Runtime::new().unwrap();
    rt.block_on(task);
}
```

**Comment by jonhoo** [comment]
I chatted briefly to @davidbarsky about this yesterday, and the difference between
```rust
tokio::run(task);
```
and
```rust
let mut rt = Runtime::new().unwrap();
rt.block_on(task);
```
is that `tokio::run` [won't return](https://github.com/tokio-rs/tokio/blob/9f356d62443210277758c63a7ee816a78965b54a/src/runtime/threadpool/mod.rs#L101L107) until the `Runtime` becomes idle (as in, `shutdown_on_idle`). This is probably because `hyper` spawns some futures (like the connection pool) which doesn't shut down (and make the `Runtime` idle) until the `Client` has been dropped. So, if you change the code to read:
```rust
drop(client);
tokio::run(task);
```
I'd guess that it'll work just fine. And that's also slightly cleaner than to just drop the `Runtime` as you're doing with `rt.block_on`.

**Comment by lukaseller** [comment]
Thanks very much - this answers my question.

**Comment by dtantsur** [comment]
Hi folks! Should we fix the client example https://github.com/hyperium/hyper/blob/master/examples/client.rs then? It uses `hyper::rt::run`, which in turn uses `tokio::run`, which will hang the way described in this bug (I also got hit by it).
