### ISSUE TITLE
Hidden types in public interface

### ISSUE THREAD

**Issue by vorner** [hyperium/hyper#1755]
Hello

Hyper seems to like to hide types that appear in its public interface. This is sometimes limiting. Currently, I'm struggling with the `Graceful` being hidden: https://docs.rs/hyper/0.12.21/hyper/server/struct.Server.html#method.with_graceful_shutdown.

I wanted to use the return value in an associated type of a trait, which I can't. And I can't use `impl Trait` there either.

This is, however, not the first time I see something like this here. What is the problem of making the type itself public, but without any public methods to manipulate it?

**Comment by seanmonstar** [comment]
Truthfully, that should really just return `impl Future`, instead of the named `Graceful`...

**Comment by vorner** [comment]
That wouldn't really improve my situation with associated types in a trait, though :-(.

**Comment by seanmonstar** [comment]
It's not publicly exported so that the details aren't relied upon, such as the extra number of generics, or their exact bounds. For now, it can be converted into a `Box<Future>`, or if clever, you can do some shenanigans to get an `impl Future` into an associated type (kind of like how you can do so with `service_fn`). Soon-ish, we can put existential types in traits.
