### ISSUE TITLE
There are no Client examples where something is actually returned from the future

### ISSUE THREAD

**Issue by kirhgoff** [hyperium/hyper#1815]
Probably I am missing something. But I am looking here 
https://hyper.rs/guides/client/basic/
and in some other places and cannot figure out how can I actually return something from any request. All the examples usually just have `.map` call and print something. 

The problem is that when I am trying to call `.wait()` directly on a Future, it gives me an error:
```
tokio::spawn failed (is a tokio runtime running this future?)
```
and `rt::run()` does not have a return value. How could I get real data returned by the Future outside of a future? Any examples? Like it was in old version
```
 let res = http_client.post(URL).body(payload).send();
```

**Comment by seanmonstar** [comment]
There's an [example returning some object decoded from JSON](https://github.com/hyperium/hyper/blob/master/examples/client_json.rs).

> The problem is that when I am trying to call `.wait()` directly on a Future

You shouldn't be using `Future::wait`, it causes problems when called on nested futures (as you've seen), and is removed in new versions (futures@v0.3). You also can't return a value from `rt::run`, since it's essentially `fn main` for the runtime.
