### ISSUE TITLE
Destination should provide accessor to uri::Authority

### ISSUE THREAD

**Issue by mzabaluev** [hyperium/hyper#1826]
It is unwieldy to derive an URI from `Destination`, e.g. for setting the Origin header.
One needs to get the string from `.host()` and destructure the `Option<u16>` retrieved by `.port()`, to construct an `Authority` for `uri::Builder` by parsing a temporary formatted `String` or a `BytesMut`.

Copying the authority part should be as simple as `dst.authority().unwrap().clone()`.

**Comment by seanmonstar** [comment]
This forces the representation of `Destination` to always hold an `Authority` internally, in order to return a reference to it. Rather, that `Destination` is holding a `Uri` is just an implementation detail. Therefore, I wouldn't want to go in this direction (there is the question of if `Destination` should be a thing, but that's a little off-topic here).

**Comment by mzabaluev** [comment]
An `impl TryFrom<Destination> for Uri`, or a fallible `.to_uri()` method, would also do what is needed without exposing an internal representation.
