### ISSUE TITLE
How to implement HTTP/1.1 long-poll responses?

### ISSUE THREAD

**Issue by pnehrer** [hyperium/hyper#1989]
Hi, I'm trying to implement a long-poll endpoint (a-la [Server-Sent Events](https://html.spec.whatwg.org/multipage/server-sent-events.html#server-sent-events)) but I can't seem to be able to figure out how to flush each individual response chunk. Using Response::channel()'s send_data appears to buffer data until the Sender is dropped (or buffer full).

What would be the best way to implement this?

**Comment by seanmonstar** [comment]
hyper will automatically flush the write body data. Is it possible the chunks are tiny and Nagle's is slowing down the flush?

**Comment by pnehrer** [comment]
I don't think that's it... I have tcp_nodelay set to true. Even so, I see no bytes on the client side until I send multiple chucks of 1000 bytes (even over several seconds -- the delay doesn't matter). I can provide a short example later tonight.

**Comment by pnehrer** [comment]
Here's a stripped down demonstration of the issue: https://github.com/pnehrer/hyper-flush-demo

On nightly toolchain:

`RUST_LOG=debug cargo run`

Then `curl -i localhost:3000/` and in another terminal:

`(for i in {0..400}; do echo -n 0123456789; done) | curl -i localhost:3000/ -d @-`

You should see content in first terminal only after running the second curl at least twice (I asume to fill the 8k buffer?). You will also see the remaining buffered content when terminating the process.

**Comment by seanmonstar** [comment]
Ah, I think you *might* be seeing an issue due to a different problem: the `Body::channel` uses a channel with only 1 buffer slot, and you're calling `sender.try_send_data`, which won't wait for the channel to have a free slot.

Consider: `(for i in {0..400}; do echo -n $i; done) | curl -i localhost:3000/ -d @-`. Depending on the order that the tasks are scheduled, you may have not receive all 400 numbers.

To fix your example, you try a few things:

- Use `tx.send_data(chunk).await`, which will wait until there is space in the body channel. However, since you have a lock on the mutex, you'll likely start to see problems at scale.
- Create a channel with a bigger buffer. This would solve some of the issues, though you'd still need to accept that if the client isn't reading on the TCP stream, eventually some events would need to be lost (unless you used an unbounded channel, I suppose).
