### ISSUE TITLE
Other Transfer-Encodings, such as Gzip, Compress, Deflate, etc

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#2]

**Comment by untitaker** [comment]
Some servers send me a gzip-compressed response without me asking for it, so practically I must always be prepared for such responses.

Unfortunately the RFC's language isn't very clear what the server is supposed to do if no `Accept-Encoding` header is sent. From RFC 2616:

>If no Accept-Encoding field is present in a request, the server MAY assume that the client will accept any content coding.

https://tools.ietf.org/html/rfc2616#section-14.3

From the newer RFC 7231:

>A request without an Accept-Encoding header field implies that the user agent has no preferences regarding content-codings.  Although this allows the server to use any content-coding in a response, it does not imply that the user agent will be able to correctly process all encodings.

https://tools.ietf.org/html/rfc7231#section-5.3.4

**Comment by untitaker** [comment]
See also https://stackoverflow.com/questions/8364640/how-to-properly-handle-a-gzipped-page-when-using-curl

**Comment by seanmonstar** [comment]
A header of "Accept-Encoding: identity" means the user agent is
specifically requesting no compression. Does that help your case?

**Comment by untitaker** [comment]
Probably, though I'd still prefer if Hyper handled this transparently for me (even if behind a featureflag).

Would setting this as a default header (on Hyper's side) be acceptable?

**Comment by seanmonstar** [comment]
I'm not so certain that this is a decision that hyper should default to. As you noticed in 7231, sending no header is valid, and implies no preference. If a user of hyper hasn't stated otherwise, I don't think we can assume a preference.

A higher level Client wrapper would probably be the place to be more opinionated, methinks.

**Comment by untitaker** [comment]
This has bitten me again. This time a different library, @simonsapin's [kuchiki](https://github.com/SimonSapin/kuchiki) provides a `parse_html().from_http(url)` interface, but doesn't explicitly set a header. The result is a garbage DOM.

>If a user of hyper hasn't stated otherwise, I don't think we can assume a preference.

If a user of hyper hasn't stated otherwise, I don't think we can assume they'd thought about it.

**Comment by seanmonstar** [comment]
Again, does asking for identity fix the issue?

**Comment by untitaker** [comment]
Sorry, it seems to be an issue with the server in this case.

**Comment by SimonSapin** [comment]
(@untitaker I’ve extended kuchiki’s `from_http` to also except an `hyper::client::Response` so that you can set headers and make the request yourself. In that case, the point of using it `from_http` instead of `read_from` with a `Response` as a generic `std::io::Read` is that it gets the `charset` from `Content-Type`, if any.)

**Comment by Trolldemorted** [comment]
@seanmonstar is it possible to set the headers once per client, so that we don't have do add them with every request?

**Comment by seanmonstar** [comment]
@Trolldemorted not in hyper. Such a feature [does exist in reqwest](https://docs.rs/reqwest/0.8.5/reqwest/struct.ClientBuilder.html#method.default_headers), though!
