### ISSUE TITLE
How to limit connections create rate?

### ISSUE THREAD

**Issue by IamFake** [hyperium/hyper#2108]
Hi. My api provider have limits on new connections on per second basis, but do not limit requests per single connection. How I can limit connections create rate in hyper? And could i? What the best way?

**Comment by davidbarsky** [comment]
This library isn't yet documented very well, but you can make use of [Tower's `RateLimit`](https://docs.rs/tower/0.3.0/tower/limit/rate/index.html). You'd make use of the ServiceBuilder, which is [documented here](https://docs.rs/tower/0.3.0/tower/builder/struct.ServiceBuilder.html#examples). Since `hyper::Client` implements `tower::Service`, you can pass in a built client to the [`ServiceBuilder::service`](https://docs.rs/tower/0.3.0/tower/builder/struct.ServiceBuilder.html#method.service) call.

**Comment by seanmonstar** [comment]
There isn't a setting on the `Client` that would allow you to do this. You'd need to create your own connection pool using the lower-level `hyper::client::conn` types.
