### ISSUE TITLE
impl From<&mut dyn Read> for Body

### ISSUE THREAD

**Issue by IcanDivideBy0** [hyperium/hyper#2137]
I'm currently building dynamic pdf with [`wkhtmltopdf`](https://crates.io/crates/wkhtmltopdf), the crate expose a [`PdfOutput`](https://docs.rs/wkhtmltopdf/0.3.0/wkhtmltopdf/struct.PdfOutput.html) struct which implement [`Read`](https://doc.rust-lang.org/std/io/trait.Read.html).

I can't figure a way to send the pdf as a response without converting it to a `Vec<u8>`, which i'd prefer to avoid since it will move the whole buffer to the heap.

```rust
let pdf: PdfOutput = ...;

// not really an ideal solution...
// let buf = pdf.bytes().collect::<Result<Vec<u8>, _>>().unwrap();

// would be much better IMO
let buf: &mut dyn Read = &mut pdf;

Response::builder()
    .header(header::CONTENT_TYPE, "application/pdf")
    .body(buf)
```

Is there a particular reason that `From<dyn Read>` is not implemented for `Body` ? I think this would be a nice addition, would you consider a PR adding this ?

**Comment by seanmonstar** [comment]
> Is there a particular reason that From<dyn Read> is not implemented for Body?

There is a reason! It's because the `std::io::Read` trait describes *blocking* reads, and hyper uses non-blocking IO (and so doesn't use multiple threads by default). Passing some `std::io::Read` type could allow a `File` or similar type which would block the thread while reading, harming the HTTP server.

----

Where is the data of the `PdfOutput` saved? Is it in a file? If so, you try using `tokio::fs::File` to get an async-friendly file, and then convert that into a `Stream`.
