### ISSUE TITLE
Expose an `AddOrigin` service

### ISSUE THREAD

**Issue by LucioFranco** [hyperium/hyper#2178]
Its common in more lower level service configurations that we need to add an origin to each request. We should provide this utility since we already have all the types imported.

**Comment by seanmonstar** [comment]
Sure, this could be `hyper::service::AddOrigin` (`WithOrigin`?).

**Comment by mayankshah1607** [comment]
Hi! I'd love to take up this issue. This is the first time I'm contributing to a Rust project, so I'd really appreciate any form of help. Thanks :)

**Comment by mayankshah1607** [comment]
Hey @seanmonstar @LucioFranco 
I looked into the code, but I just have a quick (or rather noob) question - where and how exactly is this utility to be implemented? Do we have to implement this one as another trait, or a helper function to set the origin header on `Request`?
Thanks :)

**Comment by gokulchandra** [comment]
First version of what a potential solution for this could look like: https://github.com/hyperium/hyper/pull/2242

**Comment by gokulchandra** [comment]
@seanmonstar I have updated the solution for this.. #2256 .. Keen to get your feedback.

**Comment by seanmonstar** [comment]
In the back of my mind, I was thinking that we want to start pruning things from hyper to prepare for 1.0, and this addition doesn't seem essential enough to add. That's different from what we were thinking last year when the issue was written. I believe something like this could easily exist, but probably part of the `tower` set of crates, instead of hyper.
