### ISSUE TITLE
Client and server mods as feature toggles

### ISSUE THREAD

**Issue by softprops** [hyperium/hyper#2223]
When using hyper in libraries I often find myself using it in one of two ways and not often both at the same time. I'm either writing clients or servers. Servers can contain clients for other servers in application contexts but in library contexts I find this often not the case.

There is some discussion going on in rusoto about bundled client sizes (https://github.com/rusoto/rusoto/issues/1722) there are multiple factors that contribute to this but I'd like to try and make strawman argument for being able to reduce it's hyper bindings down to only what is needed for a client sdk.

Before putting potentially wasted effort into this, I wanted to see if you think there are good reasons why this might not yield meaningful value or of you know of others actively doing this research already.

**Comment by seanmonstar** [comment]
I've wanted to provide this before, but wasn't sure how badly this was desired, and I started running into annoyances of internal code that was "unused" when one or both features aren't enabled, so I gave up. If it's desirable to add, then I think these requirements exist:

- This is a breaking change, so wouldn't be available for 0.13. This is because users that have `default-features = false` would suddenly see their code break if `client` or `server` were to disappear.
- What does it mean if both features are disabled? Should that be allowed, or should we have a `compile_error!` in that case?

**Comment by softprops** [comment]
Thank's for the considerate and thoughtful response. 

I'll leave this issue open for now to see if accumulates some responses, in support of or otherwise, to gauge interest.

**Comment by seanmonstar** [comment]
I'd like to land this in the upcoming 0.14 release. @softprops do you want take this on now?

**Comment by softprops** [comment]
I could give it a shot. Could this be as simple as a set of cargo features enabled by default that when enable conditionally wire into lib.rs around [here](https://github.com/hyperium/hyper/blob/71f340242120f1ea52c7446b4bae37b894b83912/src/lib.rs#L61)?

**Comment by seanmonstar** [comment]
Probably yes, with complexity likely hiding just below the surface. I'd say start with `client` and `server` features, disabling those modules if not enabled. The complexity is likely tagging the internal code that becomes "unused" then.

For example, I'm doing a similar thing in #2251 (http2 done, http1 in progress).

**Comment by seanmonstar** [comment]
I've done this in #2333 and #2334.
