### ISSUE TITLE
HEAD request using http/2 fails on bodies that don't implement is_end_stream

### ISSUE THREAD

**Issue by jeromegn** [hyperium/hyper#2279]
Trying to do a HEAD request on an http/2 server that uses response bodies that don't implement `HttpBody::is_end_stream` (so that it sometimes return `true`) fail with an http2 protocol error.

I noticed this while wrapping a `hyper::Body` but not passing though `is_end_stream`

**Comment by seanmonstar** [comment]
Yea, we should update the `proto::h2::client` module to check for `HEAD` requests, like h1 does, and if so, then assume there can't be any request body at all.

**Comment by seanmonstar** [comment]
@jeromegn have you seen *other* HTTP2 implementations returning an error because of this? Or only `h2`? If only Rust, then have you seen this issue since https://github.com/hyperium/h2/pull/490 was merged and released?

I worry that just because a `Method` doesn't normally have a body, it could still be allowed, and it might still send trailers anyways, so just curious if we don't need to fix this specifically.

**Comment by jeromegn** [comment]
Hmm, I've fixed the issue by properly passing through all methods to my wrapped `Body` (by re-implementing `is_end_stream`).

I don't believe I've encountered it since then.

Reading my initial issue, I'm a bit confused about some of the wording :sweat_smile:. I think this is only an `hyper` / `h2` issue.
