### ISSUE TITLE
Use of Mucell in the header representation can be used to cause memory unsafety

### ISSUE THREAD

**Issue by reem** [hyperium/hyper#230]
Shared ownership of the Headers struct can be used to create aliasing `&` and `&mut` pointers through a memory safety hole in Mucell release builds. See: https://github.com/chris-morgan/mucell/issues/9

**Comment by chris-morgan** [comment]
Can it actually? The only way in which it will is if in the closure passed to `a.try_mutate()` you do something with `a`, which I don’t see happening. It’s only called twice, both times in src/header/mod.rs, and neither has this documented bad behaviour.

**Comment by seanmonstar** [comment]
I don't think the unsafety can happen because of MuCell, but instead because the value is stored inside a Cell, but we return just a plain reference to it. Once you've received the Option<&Foo>, it's lifetime is no longer connected to the Headers struct. The compiler will allow you to modify the value internally, and you'll have a dangling pointer.

The safe fix would be to create some sort of `H` smart pointer, and return that instead of a transmuted `&T`.

**Comment by chris-morgan** [comment]
Of, you're doing things like that, are you? That is bad and needs to be
fixed. In Teepee I went to great lengths to ensure total memory safety,
with such things as the TypedRef type.
