### ISSUE TITLE
`Location` should wrap around `Url`, not just `String`

### ISSUE THREAD

**Issue by kstep** [hyperium/hyper#243]
One way to solve it, is pass base `Url` (or configured `UrlParser`) to header parsers, but it looks not generic enough for me. I propose passing around `Response`/`Request`, so header parsers stay generic. And to do it right, we should implement some common trait (like `HttpContext`) for both `HttpResponse` and `HttpRequest`, and then pass it to header parser.

**Comment by kstep** [comment]
If you approve this way of action, I can try to implement it.

**Comment by pyfisch** [comment]
+100

**Comment by kstep** [comment]
@reem, what do you think?

**Comment by seanmonstar** [comment]
The most common case that would help is having access to the `Url` of the request/response. This would help with parsing the `Location`, `Referer`, `SetCookie`, etc headers.

Some other headers may benefit from accessing the status code, method, or other headers. However, until we have a concrete use case, I'd be wary of adding unknown things. Since the internals of the Header API only affect hyper itself, and anyone implementing custom headers, and not the public Client or Server interface, I'm fine with breaking changes that show up later.

That said, I'd be fine with `Header::parse_header` accepting a `&Url`, or `&C where C: HttpContext`, and `HttpContext` only implements `get_url(&self) -> &Url`.

**Comment by kstep** [comment]
@seanmonstar actually I thought about similar design, although i wanted to expose `get_headers()` method on `HttpContext` as well. It looks like it takes much more effort to implement it, not due to feature complexity, but because of number of changes in existing code needed to pass this additional argument around.

**Comment by pyfisch** [comment]
@kstep I am rewriting currently headers so do not hesitate to change it.

**Comment by seanmonstar** [comment]
I'm not sure anymore that always trying to convert the `Location` header (and similar headers) into a `Url` is correct. I'm going to close, but I could entertain the idea of instead have the header be an enum, such as:

```rust
enum Location {
    Absolute(Url),
    Relative(String),
}
```

Depends on of if that separation is useful to people, or if they'd rather just decide that for themselves.
