### ISSUE TITLE
Replace usage of `mem::uninitialized` with `MaybeUninit`

### ISSUE THREAD

**Issue by memoryruins** [hyperium/hyper#2532]
When the following comment was added in #1845, hyper's minimum supported rust version was `1.27.0`

https://github.com/hyperium/hyper/blob/4e9a006498c7bdb5bb2ccb76a4c877f6da7e23b2/src/proto/h1/role.rs#L1-L3

which I assume is why [`std::mem::MaybeUninit`](https://doc.rust-lang.org/std/mem/union.MaybeUninit.html), stabilized in `1.36.0`, could not be used yet. Today, hyper's MSRV is `1.46.0`, so it should now be possible to investigate removing the `#![allow(deprecated)]`.

**Comment by seanmonstar** [comment]
Good call!

**Comment by mohsen-alizadeh** [comment]
Refactored the code.

**Comment by Soveu** [comment]
One problem with refactoring the code is that [httparse::Request::new](https://docs.rs/httparse/1.4.0/httparse/struct.Request.html#method.new) accepts `&mut [Header]`, so it is assumed that they are initialized. It would need to accept `&mut [MaybeUninit<Header>]`

Otherwise `MaybeUninit::uninit().assume_init()` (like it is done above) gives the same problems as `mem::uninitialized`

**Comment by RalfJung** [comment]
FYI, this seems to be one of the major sources of regressions in https://github.com/rust-lang/rust/pull/87041.
