### ISSUE TITLE
Consider removing "dispatch dropped without returning error"

### ISSUE THREAD

**Issue by nox** [hyperium/hyper#2649]
**Is your feature request related to a problem? Please describe.**
Hyper panics with "dispatch dropped without returning error" if the background dispatch task goes away, either because the runtime was dropped or some user-provided code such as a HttpBody implementation panicked

**Describe the solution you'd like**
Hyper should catch the panic and return a proper error instead of panicking with "dispatch dropped without returning error".

Cc @seanmonstar

**Comment by seanmonstar** [comment]
Yea, we can do better. We probably can't completely remove the panic, since the `Canceled` error is part of the oneshot contract. But we can improve two the existing cases that _can_ happen, to try to eliminate it so that panic never _can_ happen.

- The runtime is dropped, killing the dispatch task.
- The dispatch task panics, due to user code.

We can add a `Guard` to the `oneshot::Sender` (`Callback`) to make it send an appropriate `hyper::Error` in drop, if not consumed. If `std::thread::panicking()`, then we can send an error about the dispatch task having panicked. If not, we can send an error about an unexpected runtime dropping the task.

**Comment by jyn514** [comment]
I'm seeing this panic in real code, it would be nice to avoid it somehow. Not sure how it happens.
![image](https://user-images.githubusercontent.com/23638587/152813657-da35a81f-00f3-4c7a-91e2-515d3e30cd22.png)
