### ISSUE TITLE
`hyper::Error` should either print `source` in display xor return a `Some` from `Error::cause()`, not both

### ISSUE THREAD

**Issue by nagisa** [hyperium/hyper#2732]
**Version**
f1b89c117cffebed4b2b8eb2d221fd9b25c1d3d1

**Platform**
Any

**Description**
Today the `std::fmt::Display` impl for `hyper::Error` has the following snippet:

https://github.com/hyperium/hyper/blob/f1b89c117cffebed4b2b8eb2d221fd9b25c1d3d1/src/error.rs#L500-L501

and the `std::error::Error::source` impl for `hyper::Error` reads as such:

https://github.com/hyperium/hyper/blob/f1b89c117cffebed4b2b8eb2d221fd9b25c1d3d1/src/error.rs#L510-L513

This is somewhat problematic for code that properly prints out the error causation chain. e.g. I have seen an error like this:

```
error: error trying to connect: tcp connect error: Connection refused (os error 111)
caused by: tcp connect error: Connection refused (os error 111)
caused by: Connection refused (os error 111)
```

this is pretty unreadable. Now one might argue that `hyper::Error::description()` serves this use-case, and while that's true, it seems pretty awkward to pull in hyper into the code that's implements error presentation layer just to downcast and check for `hyper`.

**Comment by seanmonstar** [comment]
See also #2542

**Comment by seanmonstar** [comment]
I should probably write up some thoughts as to why this is currently the way it is.

Wrapping an error (so that there's an inner source) frequently provides more context that is useful to users. Without showing the source, the extra context can lose some of its meaning. For example, seeing just "error trying to connect" is also too vague, just as "Connection refused" can be. Most users of hyper tend to just log the `Display` output of the error, without anything fancy. So the format for hyper is to default to be most useful to them.

I recognize that makes it more verbose for people using utilities to crawl the source chain. I currently chose to cater to the more common case.

I'm also aware that the "error working group" currently recommends against doing what hyper does. But I don't agree, since it means hurting the common case. And since I believe most users will generally just default to logging `{}` of an error, I don't think "more education" will fix that. Thus, I'd suggest that the WG consider instead that errors print their source chain by default, and allow advance users to opt-in to custom formatting. I explored this concept in https://github.com/seanmonstar/errors/issues/1, and have a not-published crate that does this, even...

**Comment by nox** [comment]
@seanmonstar What do you think of making `{:#}` not print the source parts?
