### ISSUE TITLE
Is there a way to set retry and max retry times for client request ? 

### ISSUE THREAD

**Issue by mingmwang** [hyperium/hyper#2935]
**Is your feature request related to a problem? Please describe.**

Is there a way to set the retry times for failed client requests? 

And regarding the client connection settings, besides the keep-alive settings, is there a way to set an idle time to close the connection? We want to reuse the connection as much as possible, but if there is no real traffic(except for pings) within a time(say 30 mins), we want the connection to be closed.

    let endpoint = tonic::transport::Endpoint::new(dst)?
        .connect_timeout(Duration::from_secs(20))
        .timeout(Duration::from_secs(20))
        .tcp_keepalive(Option::Some(Duration::from_secs(3600)))
        .http2_keep_alive_interval(Duration::from_secs(300))
        .keep_alive_timeout(Duration::from_secs(20))
        .keep_alive_while_idle(true);

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mingmwang** [comment]
In Netty, there is an IdleStateHandler which can trigger event to close the idle tcp connections. Not sure whether Hyper has a way to achieve the same effects or not.

**Comment by seanmonstar** [comment]
hyper does not retry requests. Looks like you're using tonic, which integrates with `tower`. You can use the [`tower::retry`](https://docs.rs/tower/latest/tower/retry/index.html) middleware to do so. Define a `Policy` that describes what responses/errors are _safe_ to retry, and I recommend using the `Budget` in the same module to implement a limit, instead of a simple counter.

**Comment by seanmonstar** [comment]
We have an issue of the ways we're making generic retries better, you can follow along (and give feedback) here: https://github.com/tower-rs/tower/issues/682
