### ISSUE TITLE
Thread pool size issue

### ISSUE THREAD

**Issue by Ap0ph1s** [hyperium/hyper#322]
After some days of diagnosing my website because of latency issues, a friend from IRC (@jshs) and I started testing the website by having multiple open connections, and have come to the conclusion that hyper's thread pool size is too small, this is what we came up with:
small thread pool size + keepalive + no timeouts => server blocked

we tested this using this python script:

https://gist.github.com/jshs/e38eef7aa2c360aef696

and it stopped after trying to send the 2nd request, and the website after was unresponsive.
since sometimes this happens when 2 people connect using browsers, it would take about 60s to
load the page, after the other connection is closed.

Could this be fixed with increasing the thread pool size on hyper's side?

VPS specs: single core

**Comment by reem** [comment]
Hyper's thread pool size is tunable using http://hyperium.github.io/hyper/hyper/server/struct.Server.html#method.listen_threads.

**Comment by reem** [comment]
We do have an issue for pervasive timeouts: #315

**Comment by renato-zannon** [comment]
@Ap0ph1s I don't know if this is a satisfactory answer for you, but on the web app world it's common to use a reverse proxy (commonly nginx) to serve static files and deal with slow clients. Since nginx is event-driven, it doesn't need a big thread pool to handle a big number of clients, and you can remove that concern from your backend server.

**Comment by Ap0ph1s** [comment]
@renato-zannon Thanks! Ill keep that in mind.
