### ISSUE TITLE
Breaking change in the header! macro not documented

### ISSUE THREAD

**Issue by maximih** [hyperium/hyper#490]
I updated to 0.3.15 and my code is now failing due to changes in `header!` macro:

```
src/lib.rs:250:43: 250:44 error: unexpected end of macro invocation
src/lib.rs:250 header!{ (TenantId, "TenantId") => [String] }
```

This is most likely due to commits https://github.com/hyperium/hyper/commit/efd6c96a3cf152b49b672ac87e225e45ab87a477 and https://github.com/hyperium/hyper/commit/a27e6812b9db98fd8f375f2b4b497e4bafc1871e which are not listed as breaking changes. 

With the new `header!` implementation It seems I must also add a dummy test function when implementing the header which is, IMHO, an unnecessary complication and makes the `header!` macro harder to use. E.g. for my example above: 

```
header!{ (TenantId, "TenantId") => [String] test1 {} }
```

Is this the intended behaviour?

**Comment by maximih** [comment]
cc @pyfisch as he is the one which added the commits mentioned above

**Comment by seanmonstar** [comment]
I'd say this was an oversight. We shouldn't have made a breaking change. A reason making it easier to miss is that all of our internal uses *do* include a test function.

I think part of a fix so as to make sure we don't break the exported `header!` macro in the future is to use it in the `examples/` directory.

**Comment by pyfisch** [comment]
Sorry, I forgot to add BREAKING CHANGE warnings to the commits. The current behaviour is the intended behaviour.

It is impossible (I think so) to add optional parts to a macro without duplicating the definition, since every header should have tests this is no problem for the core of hyper. I think also external headers should have tests, they have been proven useful to discover bugs in header parsing and formatting inside hyper. Using the `test_header!` macro makes it really easy to test headers but it requires to be inside the `header!` macro. #489 will allow external code to use it in tests, but you can also write your own test functions inside the `header!` macro test section.

**Comment by seanmonstar** [comment]
@pyfisch can't the macro be written such that without the test pattern, a dummy empty one is created?

```rust
macro_rules! header {
  ( $foo:ty $bar:ty ) => ( header! { $foo $bar test_dummy {} } )
}
```

**Comment by pyfisch** [comment]
@seanmonstar yes this will probably work.

**Comment by pyfisch** [comment]
There is one problem: you can't have multiple headers with no tests in one module, because there will be multiple `test_dummy` modules.

**Comment by maximih** [comment]
I guess you can append the `ident`to the name of the test function as the `ident` has to be unique anyhow.

**Comment by pyfisch** [comment]
Joining identifiers like function or module names does not work.

**Comment by reem** [comment]
grumbles something about macros not being hygienic even though they are supposed to be
