### ISSUE TITLE
Allow creating a String from a RequestBuilder

### ISSUE THREAD

**Issue by gsingh93** [hyperium/hyper#554]
I'd like to be able to get a String from a `RequestBuilder` to pass to my own socket. It would also be nice to examine requests as strings for debugging.

**Comment by seanmonstar** [comment]
Get a string for your own socket? Help me understand a little more... what are you using a `Client` for if you're managing your own sockets?

Also, getting a String would probably be hard, since anything added as `body()` can be plain bytes. For debugging, I could see an implementation of `fmt::Debug` being added to `RequestBuilder`.

**Comment by gsingh93** [comment]
I don't need the client, I really just want a standalone `RequestBuilder`. It could possibly return a struct that contained the status line and headers as a `String` and a `Vec<u8>` for the body.

I'm currently using hyper to convert the headers into a `String` in a type safe way (`Headers` implements `Display`), and then manually prepending the status line, appending `\r\n`, and appending the body. It would be nice to be able to build the complete request.

And in any case, adding a `Debug` impl to `RequestBuilder` could be a general improvement (although not my main motivation).

**Comment by seanmonstar** [comment]
Hm, this doesn't seem like the solution then. If you just wish to use `hyper::{headers, status, version}`, then I'd build the outgoing message manually.
