### ISSUE TITLE
Origin Header

### ISSUE THREAD

**Issue by fuchsnj** [hyperium/hyper#651]
It seems like the "Origin" header is missing  [here](http://hyper.rs/hyper/hyper/header/index.html)

http://tools.ietf.org/id/draft-abarth-origin-03.html

**Comment by seanmonstar** [comment]
Is this in common use? I've never used it myself, and when checking the dev consoles, I notice neither Firefox nor Chrome set that header while browsing.

**Comment by untitaker** [comment]
The Origin header is set for CORS requests.

On 15 October 2015 01:36:27 CEST, Sean McArthur <notifications@github.com> wrote:
>Is this in common use? I've never used it myself, and when checking the
>dev consoles, I notice neither Firefox nor Chrome set that header while
>browsing.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/hyperium/hyper/issues/651#issuecomment-148233353

-- 
Sent from my phone. Please excuse my brevity.

**Comment by seanmonstar** [comment]
Ah yes, quite true. I had forgotten.

**Comment by mfeckie** [comment]
@seanmonstar Is anyone working on this?  If not I'd be interested in giving it a go

**Comment by seanmonstar** [comment]
Go for it!

**Comment by untitaker** [comment]
I don't think anybody is working on this.

**Comment by puhrez** [comment]
Would love to get newly-rusty hands wet; what's going on here? 

A variety of PRs have been closed, and one (to another project?)

**Comment by untitaker** [comment]
I think the main discussion is under https://github.com/hyperium/hyper/pull/691, basically we waited until rust-url was 1.0 (where its Origin type was rewritten) and then forgot about it.

On 5 July 2016 01:21:00 EEST, Michael Perez <notifications@github.com> wrote:
>Would love to get newly-rusty hands wet; what's going on here? 
>
>A variety of PRs have been closed, and one (to another project?) 
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/hyperium/hyper/issues/651#issuecomment-230359643

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by seanmonstar** [comment]
The current type in rust-url is an enum with an `OpaqueOrigin` variant, which is not needed in the header. So, I'm thinking we do something like this:

```rust
pub struct Origin(String, String, Option<u16>);

// support default ports
impl PartialEq for Origin {
    fn eq(&self, other: &Origin) -> bool {
        if self.0 == other.0 && self.1 == other.1 {
            self.2.or_else(|| default_port(&self.0)) == other.2.or_else(|| default_port(&other.0))
        }
        false
    }
}

fn default_port(scheme: &str) -> Option<u16> {
    match scheme {
        "http" => Some(80),
        "https" => Some(443),
        _ => None,
    }
}
```

**Comment by puhrez** [comment]
@seanmonstar that seems good for a single "serialized-origin". I'm not very familiar with things (in general) but according to the [spec](https://tools.ietf.org/html/rfc6454#section-7) the value of an Origin header may actually be a vec of this implementation of Origin.
 
Aside from that in order to parse/generate, after having read [the docs](http://hyper.rs/hyper/v0.9.9/hyper/header/index.html) the `Origin` struct also needs to implement `Header` and `HeaderFormat` right?

**Comment by seanmonstar** [comment]
@puhrez since the Origin header only makes in CORS requests, may as well use the definition from the most up-to-date spec governing them: https://fetch.spec.whatwg.org/#origin-header

In that spec, the `Origin` is only ever 1 value.

Yes, a header needs to implement `Header` (and `HeaderFormat` in the 0.9x branch. If possible, the `header!` macro handles this merge of traits).

A `u16` means unsigned, so a bit isn't dedicated to the sign. This means it's range is 0-65535, which is the full range of possible ports.

**Comment by puhrez** [comment]
Ah yes, I knew it mean unsigned but for some reason (not being very used to `u`/`i` distinctions), I mixed the concepts.

re header! macro trait merging:
the idea then becomes to do something like (from the docs)
```
header! { (Origin, "Origin") => [String, String, Option[u16]] }
<insert yr impl block and default_port fn here>
```
May I assign myself to this and get on it?

**Comment by puhrez** [comment]
made a pull request incorporating the comments made above as well as trying to conform to contribution style, haven't tested it well (read: at all) yet tho :).
