### ISSUE TITLE
Parse AbsoluteUri further

### ISSUE THREAD

**Issue by reem** [hyperium/hyper#67]

**Comment by mikedilger** [comment]
@reem I think this is ideally best done with URL library, and AbsoluteURI being a subsection of a well defined Url structure.  However, that's not possible with the WhatWG URL standard's take on things.

@SimonSapin @annevk here is another example of URL parsing issue I called "hierarchy" issue.  AbsoluteURI contains (path,query,fragment) but WhatWG relative scheme parses path as part of SchemeData, so it can't be used, and another parser (duplicate code) is therefore required for parsing this part of a URL (... servers get no love from that standard).

Hyper defines an AbsoluteUri quite separate and non-interacting with Url.  I think it could be better if the URL standard didn't include Path in the RelativeSchemeData chunk, but left it separate as RFC 3986 treats Authority (3.2) and Path (3.3) separately without grouping them, and then group (path,query,fragment) together instead as a RelativeURI, or have another way to parse these because servers deal in this type of thing.

Maybe there are good reasons not to, but this is my point and I just wanted to get it out there and have it be understood.

**Comment by annevk** [comment]
If your comment is misplaced, you can remove it, no?

**Comment by seanmonstar** [comment]
The `Url` type is a sufficient type to represent this variant.
