### ISSUE TITLE
Add a Content-Length: 0 header when applicable

### ISSUE THREAD

**Issue by tynril** [hyperium/hyper#714]
When a response isn't sent in a handler, it will be sent by the Drop trait. When this happens, if no body has been written to the response, it is known that no further body will be added.

Consequently, the Drop implementation should add a Content-Length header. This will prevent the Transfer-Encoding: chuncked header to be added by default in the start() method.

**Comment by seanmonstar** [comment]
With async hyper, this doesn't happen in `Drop` anymore, but the concept can still be done.

In the Http1 state machine, if the user has indicated `Next::end()` without writing any body, this header could be added.

**Comment by matt2xu** [comment]
+1 for sending Content-Length: 0 instead of an empty chunk when dropping. This should be not done all the time though.

Indeed, in HTTP/1.1, there are cases where Content-Length is optional, and some in which it is explicitly forbidden: 1xx (Informational) responses and 204 (No Content) response. Also, when responding to a HEAD request, or when responding with a 304 (Not Modified) status, sending a Content-Length is optional and only valid if it is the same as the Content-Length that would have been sent if the request was a GET or the response was 200 (OK) respectively.

See 3.3.2 Content-Length
http://httpwg.org/specs/rfc7230.html#header.content-length

Also note that "A server MUST NOT send a Transfer-Encoding header field in any response with a status code of 1xx (Informational) or 204 (No Content).", which Hyper currently does not respect.

**Comment by seanmonstar** [comment]
This exists in master as follows: if no body was set on a request or response, then the Content-Length will be set to 0. There is some logic to not do this if it is a client request with `GET` or `HEAD`.
