### ISSUE TITLE
Hyper client discards query string when making requests

### ISSUE THREAD

**Issue by gtolle** [hyperium/hyper#75]
Hi all,

Found an issue while using Hyper's HTTP client. 

When starting the request, Hyper calls `rust-url`'s `serialize_path` function to generate the first header line, but `serialize_path` discards the query string from the URL. This breaks any GET request that depends on query parameters.

I sent a new pull request to rust-url that introduces a `serialize_path_with_query` method specifically so that Hyper can use it. 

  https://github.com/servo/rust-url/pull/38

If `serialize_path_with_query` gets merged into `rust-url`, I'm happy to create a pull request that updates Hyper to match.

**Comment by adwhit** [comment]
This issue has resurfaced, possibly due to the changes in rust-url 1.0.

https://github.com/servo/rust-url/pull/176

> serialize_without_fragment is now &url[..Position::AfterQuery]

**Comment by matt2xu** [comment]
Yep, I just witnessed the same thing. I'm under the impression that the problem is there:
https://github.com/hyperium/hyper/blob/master/src/client/mod.rs#L303

There is no mention of query anymore (or fragment for that matter). Maybe a simpler way would be to call url.set_host(None) to remove the host and port, and then url.into_string(), so everything else (path, query, fragment) is preserved.

**Comment by seanmonstar** [comment]
I've fixed this on master again, sorry for the bugs!

**Comment by matt2xu** [comment]
"again" ah I know that feeling... Thanks for fixing this!
