### ISSUE TITLE
Keep-alive in client?

### ISSUE THREAD

**Issue by pascalw** [hyperium/hyper#763]
I couldn't find anything about this in the docs so asking here.

I'm sharing a single Hyper client across multiple threads (using `lazy_static`) and noticed that by default Hyper seems to try keeping connections alive. For my use case that's great since I only ever call a single host. However I ran into issues where Hyper would start throwing connection closed errors on repeated calls a couple of minutes apart.

Is that expected? Should I retry the request in those cases? I somehow expected that Hyper would handle setting up a new connection if the old gets stuck/closed.

**Comment by seanmonstar** [comment]
Unfortunately, yes this is the current expected behavior. There are 2 ways
to determine if a socket has been closed, trying to use it, or using async
io to detect hang ups. We can't use it before you make a new request
because we have no data to send, and trying a read would block the thread
forever (since the server likely wouldn't send anything if there was no
request).

Currently, you can catch those errors and retry the request. The async
branch (mio) is nearly ready to merge, which will solve this in a different
way, if you'd like to try porting your code over early.

**Comment by pascalw** [comment]
Ok thanks that makes sense. Looking forward to the mio branch getting stable :)
