### ISSUE TITLE
mio branch: how to avoid creating App instance every request coming?

### ISSUE THREAD

**Issue by daogangtang** [hyperium/hyper#770]
hi, I do some work on [SApp](https://github.com/daogangtang/sapp-rs). SApp is a web framework based on hyper mio branch, but now meet an issue.

    let _guard = server.handle(|_| {
        
        let mut sapp = SApp::new();
        sapp.with_wrapper(MyApp);
        // register modules
        sapp.add_smodule(Biz);
        
        sapp
        
    });

each request will create a new SApp instance, with reregistering all modules and handlers, this is boring and ineffective.

how do I improve it? thank you.

**Comment by hexsel** [comment]
@daogangtang I'm curious why not put the question on [Rust at StackOverflow](http://stackoverflow.com/questions/tagged/rust), or maybe post it on the [Rust Reddit](https://www.reddit.com/r/rust/), this feels to me like the wrong vehicle for this type of question.

If I'm out of place, apologies.

**Comment by seanmonstar** [comment]
@daogangtang some things you could do it to construct an `SApp` when you construct the server, and make the factory return a reference to it, such as `move |_| { arc_sapp.clone() }`. I don't know if you need mutable access to the `SApp`. You can alternatively create a struct and implement `HandlerFactory` for your struct, instead of passing a closure, if that ends up looking cleaner.

**Comment by daogangtang** [comment]
@hexsel I notice.
