### ISSUE TITLE
how to support pipeline in async mio.

### ISSUE THREAD

**Issue by siddontang** [hyperium/hyper#789]
Hi @seanmonstar 

I know that now async client supports connection pool, the flow like:

1. get connection 
2. send request header (on_request)
3. send request body (on_request_writable)
4. receive response header (on_response)
5. receive response body (on_response_readable)
6. put the connection to pool for later reuse. 

I try to support pipeline, so after step 3, I return Next::read_and_write(), and think the handle can call step 2 again directly, but failed.
Then I try to return Next::write(), after step 5, but to my surprised, the handle call step 3 directly. 

After some tries, I think that now async hyper doesn't support pipeline, am I right?  Or later HTTP/2.0 can support it?

**Comment by siddontang** [comment]
Btw, I find that client now doesn't support connection pool now, although there is a pool implementation in pool.rs, is it?

**Comment by seanmonstar** [comment]
The Client doesn't yet pool keep-alive connections.

As for pipelining, I don't think I'll be trying to add support for it, because it's complicated, servers don't all support it well (hence most browsers don't use it), and HTTP 2 does it far better. I'd wait for HTTP 2 support.

**Comment by siddontang** [comment]
Em, I am waiting the pool mechanism and HTTP2, :-) 

Btw, what's the difference between Next::end() and Next::remove(), seem that they all terminate the transport now. So in the server, if I want to re-use the connection for next request after on_response_writable finished, return Next::end()?

**Comment by seanmonstar** [comment]
`end` signifies that the current response is done. After any flushing, it
will check if the connection is allowed to be kept alive, and if so, the
state is reset to the beginning to be used with a new request. Keep alive
is working in the server implementation.

`remove` will stop all action on the socket, and remove it from the event
loop. It will then be passed to Handler::on_remove. The default
implementation of that method will just drop the socket, so that makes
`remove` equivalent to an abort for the connection. However, you could also
use it for taking control of the socket, such as after receiving `Upgrade`
headers to websocket, you could remove the socket and give it to a
websocket library.

**Comment by siddontang** [comment]
Thank for your detailed explanation :-)
