### ISSUE TITLE
Listen on multiple addresses in async hyper

### ISSUE THREAD

**Issue by ebarnard** [hyperium/hyper#859]
Given that hyper is now async it would be great to be able to easily have a single server listen on multiple addresses.

It's already possible to get the local address of a connection via `Request::transport`.

It's not possible to implement your own `Transport` to do this as `Evented::register` is only passed one `Token`.

If you agree with this I'm happy to implement it. I think the easiest way is to let `Server` take multiple `Accept`s of the same type e.g (but with more traits so you could pass a bare HttpListener as before).

```rust
impl<I> Server<I> where I: IntoIterator, I::Item: Accept, <I::Item as Accept>::Output: Transport {
    ...
}
```

Then you could have something like this in a different crate.

```rust
enum HttpOrHttpsListener {
    Http(HttpListener),
    Https(HttpsListener),
}

impl Accept for HttpOrHttpsListener {
    ...
}
```

**Comment by seanmonstar** [comment]
Interesting. Your proposed use case is to listen on port 80 and 443 in the same event loop?

**Comment by ebarnard** [comment]
At the moment I just want to listen for http on multiple IPV4 and 6 addresses. That just seemed like a natural extension.

**Comment by seanmonstar** [comment]
While I have personal feelings on having an app run on both 80 and 443 together (I'd be that the http listener simply shoot out redirects to the 443 listener), I do believe this in general is a good thing to add.

----

This would require either modifying `Server::new` to accept 1 or more `Accept`, or add a second constructor, something like `fn listeners(listeners: Vec<T>)` (or generic over an Iterator? I dunno.)

And then internally, this would just add each of the listeners to the event loop. The only tweak would be that `scope.notifier()` piece that is used to signal the server should shutdown should only exist for 1 of these listeners, and not on all of them.

It should be fine to keep it `T: Accept`, since the common case would be an array of TcpListeners listening on different ports. Anyone who wanted different types can compose using an enum.

**Comment by ebarnard** [comment]
Everything's working. Just one last difficulty.

What should the behaviour be if the constructor is passed no listeners?

**It could return an error.**
e.g. `fn listeners<I: IntoIterator<...>>(listeners: I) -> Result<Server, NoListenersError>` (I'm reluctant to add another variant to `Error` just for this case.)

**It could panic.**
I don't like panics.

**`ServerLoop::run` dies immediately.**

**`ServerLoop::run` runs normally (with no listeners)!**
______
I'm a fan of option 4.

We wouldn't need a second constructor - `Server::new` would do :thumbsup:.

It makes sense if we add the ability to add and remove listeners while the server is running.
This could be useful from a `service apache2 reload` point of view and if you want to do a graceful shutdown (i.e. kill the listener then wait a bit before killing all the open sockets).

It's pretty easy to check if you've got no listeners and just before starting your server maybe isn't the best place to do it.

**Comment by seanmonstar** [comment]
Hm. So, you start a server with no listeners, and so you have an event loop running, essentially doing nothing? I get all the points of being able to kill the listener without killing the server, for shutdowns or restarts. I just don't know what you would do with *creating* a Server that has no listeners (until there is a definitive API to add in some listeners).

So, without that API, I'd lean towards providing zero listeners is a programmer error. That would mean a panic. I'm not for promoting panicking on everything, but this actually does seem like the right thing to do, since until there is a way to add listeners, a `Server` with no listener will only cause head scratches.
