### ISSUE TITLE
Set Host header at serialization, not at beginning

### ISSUE THREAD

**Issue by seanmonstar** [hyperium/hyper#911]
This should be simlar to how `TransferEncoding` is added only if `ContentLength` or `TransferEncoding` aren't already present.

**Comment by jwilm** [comment]
@seanmonstar thanks for the discussion on IRC about this and for filing the issue. For anyone else following, this makes setting `client::Request` headers from a `Headers` work (with 0 overhead) without worrying about any state that hyper had in the original headers map (because there won't be any!).

**Comment by tabac** [comment]
I took a quick look at this. So what you're saying is move the `Host` specific code from [here](https://github.com/hyperium/hyper/blob/master/src/client/mod.rs#L143) to somewhere in [here](https://github.com/hyperium/hyper/blob/master/src/http/h1/parse.rs#L189), right? If so, how are we  going to have access to the `Request.url()` from the second function?

Also, in the `Client` code we're creating a new `Headers` instance place the `Host` first and extend with the remaining headers. I assume that we do that so that the `Host` header appears first. Do we care about the order of the remaining headers? If not maybe a combination of `swap_remove` and `push` could work without iterating.

**Comment by seanmonstar** [comment]
Hm, I no longer think this should be done (doing just before serialization), since as you pointed out, the information isn't available that far down the pipeline.

**Comment by tabac** [comment]
How about this part?

> Also, in the `Clien`t code we're creating a new `Headers` instance place the `Host` first and extend with the remaining headers. I assume that we do that so that the Host header appears first. Do we care about the order of the remaining headers? If not maybe a combination of `swap_remove` and `push` could work without iterating.

It would take a few additions in `Headers`'s and `VecMap`'s implementations to expose those `Vec` methods. I know we're not gaining much but just asking.

**Comment by seanmonstar** [comment]
That the host is set first in the client implementation is for 2 reasons, I suppose:

1. To allow an explicitly set `Host` header to override the default.
2. [RFC7230](https://tools.ietf.org/html/rfc7230#section-5.4) recommends making the `Host` header the first one after the start line.

However, there are some downsides to how this is currently done. It is a little wasteful, as it copies the `Headers` struct unnecessarily. It also means that if someone *did* set a `Host` header, it is not necessarily put to the front, and so may not be printed first.

Perhaps a better solution would be:

1. Don't create a new `Headers` struct to copy in to, but instead check if there is no `Host` header, and if not, add it.
2. In `hyper::http::h1::parse`, adjust the `ClientTransaction::encode` function to wrap the `Headers` in a `HostFirstHeaders<'a>(&'a Headers)` adapter. This `fmt::Display` adapter could always write the `Host` header first, and then skip the `Host` in the iter part.
