### ISSUE TITLE
Memory pooling

### ISSUE THREAD

**Issue by DemiMarie** [hyperium/hyper#927]
This is a feature request for the use of memory pooling in Hyper, to reduce allocations despite the use of asynchronous IO.

See [this blog post](http://www.rubyraptor.org/how-we-made-raptor-up-to-4x-faster-than-unicorn-and-up-to-2x-faster-than-puma-torquebox/) for more details.

**Comment by seanmonstar** [comment]
Did you have specific concerns for hyper?

**Comment by DemiMarie** [comment]
@seanmonstar Basically performance.  I would like to see Hyper be as fast at HTTP as any server/client written in C or C++.

**Comment by DemiMarie** [comment]
@seanmonstar I am thinking of the various `String` and `Vec` allocations for data structures such as HTTP headers, as well as the parser objects themselves.

**Comment by seanmonstar** [comment]
I do think it'd be interesting to be able to use  a pool for it all, and
reduce the number of owned allocations. I also think it will be tedious
work to fully accomplish, and profiles don't show that allocation is a
concern at the moment.

**Comment by DemiMarie** [comment]
@seanmonstar What is the bottleneck currently?

**Comment by pyros2097** [comment]
Well this https://github.com/valyala/fasthttp for go surpassed the go's standard http library almost 10x by using pools and buffers a lot. Maybe this would improve hyper's response times under heavy loads only. Pooling requests, requests, responses, buffers, streams ...etc

**Comment by seanmonstar** [comment]
Rust doesn't have a GC that it needs to do dances around, like Java or Go, so there's less concern with creating objects on the stack. Strings make use of `Bytes`, which allow refcounted slices instead of copying and allocating. And there's also now a super basic "cached `HeaderMap`" for a connection, reusing a possible allocation.

So, I'm going to close this general issue down as fixed. If there are specific pieces that could still benefit, we can open specific issues for those things. :D
