### ISSUE TITLE
Using https://github.com/briansmith/ring instead of OpenSSL

### ISSUE THREAD

**Issue by lygstate** [hyperium/hyper#956]
That's a version porting to pure rust.

**Comment by sfackler** [comment]
I don't believe *ring* implements TLS.

**Comment by lygstate** [comment]
How about rusttls?

**Comment by lygstate** [comment]
https://github.com/ctz/rustls,
it's using ring

**Comment by sfackler** [comment]
The https://crates.io/crates/hyper-rustls crate provides RusTLS support for Hyper. I don't think it makes sense to default to RusTLS at the current time, though, since its supported feature set is pretty small. It doesn't support DHE key exchange, AES modes other than GCM, and protocols other than TLSv1.2. This means, for example, that it can't talk to Java 1.7 or lower.

**Comment by Hoverbear** [comment]
The tokio branch is now using `native_tls`.

**Comment by seanmonstar** [comment]
As explained in #985, hyper no longer picks a default TLS implementation, and any crate can provide one.
