### ISSUE TITLE
Listening.close() does not close the server

### ISSUE THREAD

**Issue by thibaultdelor** [hyperium/hyper#968]
(Not sure if it's the same issue as #338)
Listening.close() leaves the connection open.

Simple test to check the bug (to put in tests/server.rs) :
```rust
#[test]
fn server_should_stop_listening_after_close() {
    let server_socket;
    {
        let server = serve();
        server_socket = server.addr().clone();
        assert!(TcpStream::connect(server_socket).is_ok());
    }

    assert!(TcpStream::connect(server_socket).is_err());
}
```

On the second assert, the connection should have been dropped but instead it keeps listening.

**Comment by awalcutt** [comment]
I'm new to rust and hyper so I'm not super familiar with the internals here. I found that, if you sleep even a single nanosecond before the second assert

i.e. `std::thread::sleep(Duration::new(0,1));`)

the test passes. I don't know if that's expected behavior or not.

**Comment by seanmonstar** [comment]
Ah, I didn't realize that this was talking about the tokio branch. Indeed, the issue is that the signal to close in the test suite is a message sent to the server thread. It's not going to happen synchronously, though I suppose for the tests it could be possible to do so.

Instead, as suggested, waiting for the other thread to tick is required so that it can shutdown.

**Comment by awalcutt** [comment]
> Ah, I didn't realize that this was talking about the tokio branch.

For the record, I'm using hyper 0.10.0-a.0 after having cloned the master branch this morning. Anyway, glad I could help clarify the situation :)
