### ISSUE TITLE
[Tokio Branch] hyper::server::response::{ Body and IntoBody } are private, propose to expose publically

### ISSUE THREAD

**Issue by ashleysommer** [hyperium/hyper#969]
Currently, you can call `response.set_body()` with anything that implements `hyper::server::response::IntoBody`, and right now that is just `Body` itself, `Vec<u8>` and `&'static [u8]`.

In my application, I have my own ResponseBody struct, that I would like implement `IntoBody`, (to pass to `response.set_body()` but I cannot because `IntoBody` is private.

Additionally, I would like to be able to use the `hyper::server::response::Body` type, so that I can do the `Body::pair()` and `tx.start_send()` within my application, then pass that result to `response.set_body()`.

Is that potentially breaking any Hyper conventions? Are they private for a reason, and is there a better way of doing what I want to do? (Other than simply converting my ResponseBody to `Vec<u8>` and passing that in.)

**Comment by seanmonstar** [comment]
In general things are private because I'm being much more conservative with what is made public, so internal optimizations can be made without breaking people.

In this particular case, I didn't really like the idea of a `IntoBody` trait, but instead wanted `Into<Body>`. The `IntoBody` trait currently exists because I cannot `impl Into<Body> for Vec<u8>`, since neither `Body` nor `Vec<u8>` are defined in hyper. I think what is probably the best to do is to create `hyper::Body`, which may just wrap around `tokio_proto::streaming::pipeline::Body`, and so I can also kill the trait.

A reason for hyper to have its own `Body` is because once hyper supports HTTP2, it would need to use `tokio_proto::streaming::multiplex::Body`, and I'd rather take care of those details internally.

I hadn't done all this yet because, well, I've forgotten, and I also wasn't certain if it was the right thing to do, but it currently feels like it.

**Comment by ashleysommer** [comment]
Oh, yes, creating a `hyper::Body` that is just a wrapper around the `tokio_proto` `Body` is a good idea, so that you can implement `Into<Body>` on that.

Then if that `hyper::Body` was exposed publicly,

**Comment by ashleysommer** [comment]
Oh, yes, creating a `hyper::Body` that is just a wrapper around the `tokio_proto` `Body` is a good idea, so that you can implement `Into<Body>` on that.

Then if that `hyper::Body` was exposed publicly, I could do `impl Into<hyper::Body> for MyResponseBody` and be able to pass `MyResponseBody` directly into `set_body()`. That way I don't need to add a dependency on `tokio_proto` into my application, and can simply use `hyper::Body`.

**Comment by ashleysommer** [comment]
Another point to make. Currently `hyper::server::response::Body` and `hyper::client::response::Body` are both separately defined to `tokio_proto::streaming::pipeline::Body`. Would a `hyper::Body` replace both of those? Will `server::response::Body` always be the same as `server::client::Body`, regardless of what `tokio_proto` `Body` it is using?

**Comment by seanmonstar** [comment]
They should probably be the same type, and they should be made to work regardless of whether 1 side is HTTP1 and the other is HTTP2, and the type is really just meant to describe something that implements `Future<Item=hyper::Chunk, Error=hyper::Error>`.
