### ISSUE TITLE
[Tokio Branch] hyper::server::request::Request::deconstruct() does not return Request.body

### ISSUE THREAD

**Issue by ashleysommer** [hyperium/hyper#970]
As per title.
You can get a tuple with `(self.method, self.uri, self.version, self.headers)` by calling `request.deconstruct()`, that consumes `request`.
Alternatively you can get just request body by using `request.body()` but that also consumes the request.
There is no way of getting both the deconstructed request items _and_ the request body from a single request.

**Comment by Hoverbear** [comment]
Hm, should it return `Option<Body>` or just `Body`? I'm actually a bit curious why both `Some<Body::Empty>` and `None` are options when constructing a request. 

From the code it seems like it just treats `None` as `Body::Empty` anyways:

```rust
    #[inline]
    pub fn body(self) -> Body {
        self.body.unwrap_or_else(|| {
            trace!("Request::body empty");
            Body::empty()
        })
    }
```

**Comment by seanmonstar** [comment]
My reasoning for using an `Option<Body>` internally is because 1) you cannot query a `Body` to see if it is empty, so therefore 2) you cannot know from just the `Body` whether you should pass a `Message::WithBody(head, body)` or `Message::WithoutBody(head)` to tokio. Maybe it makes sense to add a method to `Body` to check if it is empty. But I don't think that it being an `Option<Body>` needs to be made known to a user. Actually, considering that it is only needed for constructing the `Message`, and `Request` is constructed **from** a Message, not into one, the option can probably be removed from `Request`...

**Comment by ashleysommer** [comment]
closed by https://github.com/hyperium/hyper/commit/f1785dc5700129db26889f55969e9f9b2e22ac7a
