### ISSUE TITLE
Hyper ContentType hard-codes `Mime<AsRef[Param]>` as `Mime<Vec<Param>>`

### ISSUE THREAD

**Issue by derekdreery** [hyperium/hyper#991]
In the mime crate, mimes can be created from `&'static [Param]`, but defaults to `Vec<Param>`. In hyper, it's not possible to use `&'static [Param]`.

The signature could be `pub struct ContentType<T: AsRef[mime::Param] = Vec<mime::Param>>(pub Mime<T>);` to avoid the heap.

**Comment by seanmonstar** [comment]
I initially set the type for `ContentType` to a vec because allowing it to be generic means each different type ends up with a different `TypeId`, which is how the typed headers are stored internally in the `Headers` type. This means that you could have this code:

```rust
let mime_with_static: Mime<&'static [mime::Param]> = ...;
headers.set(ContentType(mime_with_static));
let mime_with_vec = headers.get::<ContentType<Vec<mime::Param>>();
```

And internally, it will have treat that as two different typed headers, so they will both be stored separately.

I suppose that's not the end of the world, but at the time it seemed like a bad idea. At the same time, one can create any `struct MyDifferentContentType(Whatever)` and implement `Header`, and it will work as well.

**Comment by seanmonstar** [comment]
Closing as this was merged.
